OmniLatin = {
	'A': dict(unicode=[0x41], anchors=['top', 'bottom', 'ogonek', 'topRight', 'middle']),
	'B': dict(unicode=[0x42], anchors=['top', 'bottom', 'topRight']),
	'C': dict(unicode=[0x43], anchors=['top', 'bottom', 'topRight', 'middle']),
	'D': dict(unicode=[0x44], anchors=['top', 'bottom', 'topRight', 'middle']),
	'E': dict(unicode=[0x45], anchors=['top', 'bottom', 'ogonek', 'topRight', 'middle']),
	'F': dict(unicode=[0x46], anchors=['topRight']),
	'G': dict(unicode=[0x47], anchors=['top', 'bottom', 'topRight', 'middle']),
	'H': dict(unicode=[0x48], anchors=['top', 'bottom', 'topRight']),
	'I': dict(unicode=[0x49], anchors=['top', 'bottom', 'ogonek', 'topRight', 'middle']),
	'J': dict(unicode=[0x4a], anchors=['top', 'topRight', 'middle']),
	'K': dict(unicode=[0x4b], anchors=['top', 'bottom', 'topRight']),
	'L': dict(unicode=[0x4c], anchors=['top', 'bottom', 'topRight', 'middle']),
	'M': dict(unicode=[0x4d], anchors=['top', 'topRight', 'bottom']),
	'N': dict(unicode=[0x4e], anchors=['bottom', 'top', 'topRight']),
	'O': dict(unicode=[0x4f], anchors=['top', 'bottom', 'ogonek', 'topRight', 'middle', 'horn']),
	'P': dict(unicode=[0x50], anchors=['top', 'bottom', 'topRight', 'middle']),
	'Q': dict(unicode=[0x51], anchors=['top',' topRight']),
	'R': dict(unicode=[0x52], anchors=['top', 'bottom', 'topRight', 'middle']),
	'S': dict(unicode=[0x53], anchors=['top', 'bottom', 'topRight', 'ogonek']),
	'T': dict(unicode=[0x54], anchors=['top', 'bottom', 'topRight', 'middle']),
	'U': dict(unicode=[0x55], anchors=['top', 'bottom', 'ogonek', 'topRight', 'middle', 'horn']),
	'V': dict(unicode=[0x56], anchors=['top', 'bottom', 'topRight']),
	'W': dict(unicode=[0x57], anchors=['top', 'bottom', 'topRight']),
	'X': dict(unicode=[0x58], anchors=['top', 'bottom', 'topRight']),
	'Y': dict(unicode=[0x59], anchors=['top', 'bottom', 'topRight']),
	'Z': dict(unicode=[0x5a], anchors=['top', 'bottom', 'topRight', 'ogonek', 'middle']),

	'a': dict(unicode=[0x61], anchors=['bottom', 'ogonek', 'top', 'topRight', 'middle']),
	'b': dict(unicode=[0x62], anchors=['topRight', 'bottom']),
	'c': dict(unicode=[0x63], anchors=['top', 'bottom', 'topRight', 'middle']),
	'd': dict(unicode=[0x64], anchors=['top', 'bottom', 'topRight', 'middle']),
	'e': dict(unicode=[0x65], anchors=['top', 'bottom', 'ogonek', 'topRight', 'middle']),
	'f': dict(unicode=[0x66], anchors=['topRight']),
	'g': dict(unicode=[0x67], anchors=['top', 'topRight', 'bottom', 'middle']),
	'h': dict(unicode=[0x68], anchors=['bottom', 'top', 'topRight', 'middle']),
	'i': dict(unicode=[0x69], anchors=['bottom', 'ogonek', 'topRight', 'middle']),
	'j': dict(unicode=[0x6a], anchors=['topRight', 'middle']),
	'k': dict(unicode=[0x6b], anchors=['top', 'bottom', 'topRight']),
	'l': dict(unicode=[0x6c], anchors=['bottom', 'top', 'topRight', 'middle']),
	'm': dict(unicode=[0x6d], anchors=['top', 'topRight', 'bottom']),
	'n': dict(unicode=[0x6e], anchors=['top', 'bottom', 'topRight']),
	'o': dict(unicode=[0x6f], anchors=['top', 'bottom', 'ogonek', 'topRight', 'middle', 'horn']),
	'p': dict(unicode=[0x70], anchors=['topRight', 'top']),
	'q': dict(unicode=[0x71], anchors=['topRight', 'top']),
	'r': dict(unicode=[0x72], anchors=['bottom', 'top', 'topRight', 'middle']),
	's': dict(unicode=[0x73], anchors=['top', 'bottom', 'topRight', 'ogonek']),
	't': dict(unicode=[0x74], anchors=['bottom', 'topRight', 'middle']),
	'u': dict(unicode=[0x75], anchors=['top', 'bottom', 'ogonek', 'topRight', 'middle', 'horn']),
	'v': dict(unicode=[0x76], anchors=['top', 'bottom', 'topRight']),
	'w': dict(unicode=[0x77], anchors=['top', 'bottom', 'topRight']),
	'x': dict(unicode=[0x78], anchors=['top', 'bottom', 'topRight']),
	'y': dict(unicode=[0x79], anchors=['top', 'bottom', 'topRight']),
	'z': dict(unicode=[0x7a], anchors=['top', 'bottom', 'topRight', 'ogonek', 'middle']),

	'Aacute': dict(unicode=[0xc1], baseGlyphs=['A'], accents=['acute.cap@top'], anchors=['top', 'bottom']),
	'Abreve': dict(unicode=[0x102], baseGlyphs=['A'], accents=['breve.cap@top'], anchors=['top', 'bottom']),
	'Abreveacute': dict(unicode=[0x1eae], baseGlyphs=['A'], accents=['breveacute.cap@top'], anchors=['top', 'bottom']),
	'Abrevedotbelow': dict(unicode=[0x1eb6], baseGlyphs=['A'], accents=['breve.cap@top', 'dotbelowcmb@bottom'], anchors=['top', 'bottom']),
	'Abrevegrave': dict(unicode=[0x1eb0], baseGlyphs=['A'], accents=['brevegrave.cap@top'], anchors=['top', 'bottom']),
	'Abrevehookabove': dict(unicode=[0x1eb2], baseGlyphs=['A'], accents=['brevehook.cap@top'], anchors=['top', 'bottom']),
	'Abrevetilde': dict(unicode=[0x1eb4], baseGlyphs=['A'], accents=['brevetilde.cap@top'], anchors=['top', 'bottom']),
	'Acaron': dict(unicode=[0x1cd], baseGlyphs=['A'], accents=['caron.cap@top'], anchors=['top', 'bottom']),
	'Acircumflex': dict(unicode=[0xc2], baseGlyphs=['A'], accents=['circumflex.cap@top'], anchors=['top', 'bottom']),
	'Acircumflexacute': dict(unicode=[0x1ea4], baseGlyphs=['A'], accents=['circumflexacute.cap@top'], anchors=['top', 'bottom']),
	'Acircumflexdotbelow': dict(unicode=[0x1eac], baseGlyphs=['A'], accents=['circumflex.cap@top', 'dotbelowcmb@bottom'], anchors=['top', 'bottom']),
	'Acircumflexgrave': dict(unicode=[0x1ea6], baseGlyphs=['A'], accents=['circumflexgrave.cap@top'], anchors=['top', 'bottom']),
	'Acircumflexhookabove': dict(unicode=[0x1ea8], baseGlyphs=['A'], accents=['circumflexhook.cap@top'], anchors=['top', 'bottom']),
	'Acircumflextilde': dict(unicode=[0x1eaa], baseGlyphs=['A'], accents=['circumflextilde.cap@top'], anchors=['top', 'bottom']),
	'Adieresis': dict(unicode=[0xc4], baseGlyphs=['A'], accents=['dieresis.cap@top'], anchors=['top', 'bottom']),
	'Adieresismacron': dict(unicode=[0x1de], baseGlyphs=['A'], accents=['dieresismacron.cap@top'], anchors=['top', 'bottom']),
	'Adot': dict(unicode=[0x226], baseGlyphs=['A'], accents=['dotaccent.cap@top'], anchors=['top', 'bottom']),
	'Adotbelow': dict(unicode=[0x1ea0], baseGlyphs=['A'], accents=['dotbelowcmb@bottom'], anchors=['top', 'bottom']),
	'Agrave': dict(unicode=[0xc0], baseGlyphs=['A'], accents=['grave.cap@top'], anchors=['top', 'bottom']),
	'Ahookabove': dict(unicode=[0x1ea2], baseGlyphs=['A'], accents=['hookabove.cap@top'], anchors=['top', 'bottom']),
	'Amacron': dict(unicode=[0x100], baseGlyphs=['A'], accents=['macron.cap@top'], anchors=['top', 'bottom']),
	'Aogonek': dict(unicode=[0x104], baseGlyphs=['A'], accents=['ogonekcmb@ogonek'], anchors=['top', 'bottom']),
	'Aogonek.NAV': dict(baseGlyphs=['A'], accents=['ogonekcmb.NAV@bottom'], anchors=['top', 'bottom']),
	'Aring': dict(unicode=[0xc5], baseGlyphs=['A'], accents=['ring.cap@top'], anchors=['top', 'bottom']),
	'Aringacute': dict(unicode=[0x1fa], baseGlyphs=['A'], accents=['ringacute.cap@top'], anchors=['top', 'bottom']),
	'Atilde': dict(unicode=[0xc3], baseGlyphs=['A'], accents=['tilde.cap@top'], anchors=['top', 'bottom']),
	'Astroke': dict(unicode=[0x23a], baseGlyphs=['A'], accents=['soliduslongoverlaycmb.cap@middle'], anchors=['top', 'bottom']),
	'Alpha.LATN': dict(unicode=[0x2c6d], anchors=['top', 'bottom']),
	'Acircle': dict(unicode=[0x24b6], anchors=['top', 'bottom']),

	'AE': dict(unicode=[0xc6], baseGlyphs=['A','E'], anchors=['top', 'bottom']),
	'AEacute': dict(unicode=[0x1fc], baseGlyphs=['AE'], accents=['acute.cap@top'], anchors=['top', 'bottom']),

	'Bdotbelow': dict(unicode=[0x1E04], baseGlyphs=['B'], accents=['dotbelowcmb@bottom'], anchors=['top', 'bottom']),
	'Blinebelow': dict(unicode=[0x1E06], baseGlyphs=['B'], accents=['macronbelowcmb@bottom'], anchors=['top', 'bottom']),
	'Bhook': dict(unicode=[0x181], baseGlyphs=['B'], anchors=['top', 'bottom']),

	'Cacute': dict(unicode=[0x106], baseGlyphs=['C'], accents=['acute.cap@top'], anchors=['top', 'bottom']),
	'Ccaron': dict(unicode=[0x10c], baseGlyphs=['C'], accents=['caron.cap@top'], anchors=['top', 'bottom']),
	'Ccedilla': dict(unicode=[0xc7], baseGlyphs=['C'], accents=['cedillacmb@bottom'], anchors=['top', 'bottom']),
	'Ccircumflex': dict(unicode=[0x108], baseGlyphs=['C'], accents=['circumflex.cap@top'], anchors=['top', 'bottom']),
	'Cdotaccent': dict(unicode=[0x10a], baseGlyphs=['C'], accents=['dotaccent.cap@top'], anchors=['top', 'bottom']),
	'Cstroke': dict(unicode=[0x23b], baseGlyphs=['C'], accents=['soliduslongoverlaycmb.cap@middle']),
	'Chook': dict(unicode=[0x187], baseGlyphs=['C'], anchors=['top', 'bottom']),

	'Dcaron': dict(unicode=[0x10e], baseGlyphs=['D'], accents=['caron.cap@top'], anchors=['top', 'bottom']),
	'Dcircumflexbelow': dict(unicode=[0x1e12], baseGlyphs=['D'], accents=['circumflexbelowcmb@bottom'], anchors=['top', 'bottom']),
	'Dcommaaccent': dict(unicode=[0x1e10], baseGlyphs=['D'], accents=['commaaccentbelowcmb@bottom'], anchors=['top', 'bottom']),
	'Ddotbelow': dict(unicode=[0x1e0c], baseGlyphs=['D'], accents=['dotbelowcmb@bottom'], anchors=['top', 'bottom']),
	'Dlinebelow': dict(unicode=[0x1e0e], baseGlyphs=['D'], accents=['macronbelowcmb@bottom'], anchors=['top', 'bottom']),
	'Dhook': dict(unicode=[0x18a], baseGlyphs=['D'], anchors=['top', 'bottom']),
	'Eth': dict(unicode=[0xd0, 0x110, 0x189], baseGlyphs=['D'], accents=['overlaystrokeshortcmb@middle'], anchors=['top', 'bottom']),
	#'Dafrican': dict(unicode=[0x189], baseGlyphs=['Eth'], anchors=['top', 'bottom']),
	#'Dcroat': dict(unicode=[0x110], baseGlyphs=['Eth'], anchors=['top', 'bottom']),
	'Dstroke': dict(unicode=[0xa7c7], baseGlyphs=['D'], accents=['overlaystrokeshortcmb@middle'], anchors=['top', 'bottom']),
	'DZcaron': dict(unicode=[0x01c4], baseGlyphs=['D', 'Zcaron']),
	'Dzcaron': dict(unicode=[0x01c5], baseGlyphs=['D', 'zcaron']),
	
	'Eacute': dict(unicode=[0xc9], baseGlyphs=['E'], accents=['acute.cap@top'], anchors=['top', 'bottom']),
	'Ebreve': dict(unicode=[0x114], baseGlyphs=['E'], accents=['breve.cap@top'], anchors=['top', 'bottom']),
	'Ecaron': dict(unicode=[0x11a], baseGlyphs=['E'], accents=['caron.cap@top'], anchors=['top', 'bottom']),
	'Ecedilla': dict(unicode=[0x0228], baseGlyphs=['E'], accents=['cedillacmb@bottom'], anchors=['top', 'bottom']),	
	'Ecircumflex': dict(unicode=[0xca], baseGlyphs=['E'], accents=['circumflex.cap@top'], anchors=['top', 'bottom']),
	'Ecircumflexacute': dict(unicode=[0x1ebe], baseGlyphs=['E'], accents=['circumflexacute.cap@top'], anchors=['top', 'bottom']),
	'Ecircumflexdotbelow': dict(unicode=[0x1ec6], baseGlyphs=['E'], accents=['circumflex.cap@top', 'dotbelowcmb@bottom'], anchors=['top', 'bottom']),
	'Ecircumflexgrave': dict(unicode=[0x1ec0], baseGlyphs=['E'], accents=['circumflexgrave.cap@top'], anchors=['top', 'bottom']),
	'Ecircumflexhookabove': dict(unicode=[0x1ec2], baseGlyphs=['E'], accents=['circumflexhook.cap@top'], anchors=['top', 'bottom']),
	'Ecircumflextilde': dict(unicode=[0x1ec4], baseGlyphs=['E'], accents=['circumflextilde.cap@top'], anchors=['top', 'bottom']),
	'Edieresis': dict(unicode=[0xcb], baseGlyphs=['E'], accents=['dieresis.cap@top'], anchors=['top', 'bottom']),
	'Edotaccent': dict(unicode=[0x116], baseGlyphs=['E'], accents=['dotaccent.cap@top'], anchors=['top', 'bottom']),
	'Edotbelow': dict(unicode=[0x1eb8], baseGlyphs=['E'], accents=['dotbelowcmb@bottom'], anchors=['top', 'bottom']),
	'Egrave': dict(unicode=[0xc8], baseGlyphs=['E'], accents=['grave.cap@top'], anchors=['top', 'bottom']),
	'Ehookabove': dict(unicode=[0x1eba], baseGlyphs=['E'], accents=['hookabove.cap@top'], anchors=['top', 'bottom']),
	'Emacron': dict(unicode=[0x112], baseGlyphs=['E'], accents=['macron.cap@top'], anchors=['top', 'bottom']),
	'Eogonek': dict(unicode=[0x118], baseGlyphs=['E'], accents=['ogonekcmb@ogonek'], anchors=['top', 'bottom']),
	'Eogonek.NAV': dict(baseGlyphs=['E'], accents=['ogonekcmb.NAV@bottom'], anchors=['top', 'bottom']),
	'Estroke': dict(unicode=[0x246], baseGlyphs=['E'], accents=['soliduslongoverlaycmb.cap@middle'], anchors=['top', 'bottom']),
	'Etilde': dict(unicode=[0x1ebc], baseGlyphs=['E'], accents=['tilde.cap@top'], anchors=['top', 'bottom']),
	'Etildebelow': dict(unicode=[0x1E1A], baseGlyphs=['E'], accents=['tildebelowcmb@bottom'], anchors=['top', 'bottom']),
	'Ereversed': dict(unicode=[0x18e], anchors=['top', 'bottom', 'topRight']),
	'Schwa': dict(unicode=[0x18f], anchors=['top', 'bottom', 'topRight']),
	'Eopen': dict(unicode=[0x190], anchors=['top', 'bottom', 'topRight']),

	'Fhook': dict(unicode=[0x191], baseGlyphs=['F'], anchors=['top', 'bottom', 'topRight']),

	'Gacute': dict(unicode=[0x1f4], baseGlyphs=['G'], accents=['acute.cap@top']),
	'Gbreve': dict(unicode=[0x11e], baseGlyphs=['G'], accents=['breve.cap@top'], anchors=['top', 'bottom']),
	'Gcaron': dict(unicode=[0x1e6], baseGlyphs=['G'], accents=['caron.cap@top'], anchors=['top', 'bottom']),
	'Gcircumflex': dict(unicode=[0x11c], baseGlyphs=['G'], accents=['circumflex.cap@top'], anchors=['top', 'bottom']),
	'Gcommaaccent': dict(unicode=[0x122], baseGlyphs=['G'], accents=['commaaccentbelowcmb@bottom'], anchors=['top', 'bottom']),
	'Gdotaccent': dict(unicode=[0x120], baseGlyphs=['G'], accents=['dotaccent.cap@top'], anchors=['top', 'bottom']),
	'Gstroke': dict(unicode=[0x1e4], baseGlyphs=['G'], accents=['overlaystrokeshortcmb.cap@middle'], anchors=['top', 'bottom']),
	'Ghook': dict(unicode=[0x193],  baseGlyphs=['G'], anchors=['top', 'bottom']),
	'Scriptg': dict(unicode=[0xa7ac], anchors=['top']),

	'Hcaron': dict(unicode=[0x21e], baseGlyphs=['H'], accents=['caron.cap@top']),
	'Hcircumflex': dict(unicode=[0x124], baseGlyphs=['H'], accents=['circumflex.cap@top']),
	'Hdieresis': dict(unicode=[0x1e26], baseGlyphs=['H'], accents=['dieresis.cap@top']),
	'Hdotbelow': dict(unicode=[0x1e24], baseGlyphs=['H'], accents=['dotbelowcmb@bottom']),
	'Hbar': dict(unicode=[0x0126], baseGlyphs=['H'], anchors=['top', 'bottom', 'topRight']),
	'Hhook': dict(unicode=[0xa7aa], baseGlyphs=['H'], anchors=['top', 'bottom', 'topRight']),
	'Hturned': dict(unicode=[0xA78D], baseGlyphs=['H'], anchors=['top', 'bottom', 'topRight']),

	'Iacute': dict(unicode=[0xcd], baseGlyphs=['I'], accents=['acute.cap@top']),
	'Ibreve': dict(unicode=[0x12c], baseGlyphs=['I'], accents=['breve.cap@top']),
	'Icaron': dict(unicode=[0x1cf], baseGlyphs=['I'], accents=['caron.cap@top']),
	'Icircumflex': dict(unicode=[0xce], baseGlyphs=['I'], accents=['circumflex.cap@top']),
	'Idieresis': dict(unicode=[0xcf], baseGlyphs=['I'], accents=['dieresis.cap@top']),
	'Idotaccent': dict(unicode=[0x130], baseGlyphs=['I'], accents=['dotaccent.cap@top']),
	'Idotbelow': dict(unicode=[0x1eca], baseGlyphs=['I'], accents=['dotbelowcmb@bottom']),
	'Igrave': dict(unicode=[0xcc], baseGlyphs=['I'], accents=['grave.cap@top']),
	'Ihookabove': dict(unicode=[0x1ec8], baseGlyphs=['I'], accents=['hookabove.cap@top']),
	'Imacron': dict(unicode=[0x12a], baseGlyphs=['I'], accents=['macron.cap@top']),
	'Iogonek': dict(unicode=[0x12e], baseGlyphs=['I'], accents=['ogonekcmb@ogonek']),
	'Istroke': dict(unicode=[0x197], baseGlyphs=['I'], accents=['overlaystrokeshortcmb@middle'], anchors=['top', 'bottom']),
	'Itilde': dict(unicode=[0x128], baseGlyphs=['I'], accents=['tilde.cap@top']),
	'Itildebelow': dict(unicode=[0x1e2c], baseGlyphs=['I'], accents=['tildebelowcmb@bottom']),
	'Ismall': dict(unicode=[0xa7ae], anchors=['top', 'bottom']),
	'Iota.LATN': dict(unicode=[0x196], anchors=['top', 'bottom']),

	'IJ': dict(unicode=[0x0132], baseGlyphs=['I', 'J'], anchors=['top']),
	'IJacute': dict(baseGlyphs=['IJ'], accents=['acute.cap@top', 'acute.cap@top']),

	'Jcircumflex': dict(unicode=[0x134], baseGlyphs=['J'], accents=['circumflex.cap@top']),
	'Jstroke': dict(unicode=[0x248], baseGlyphs=['J'], accents=['overlaystrokeshortcmb@middle'], anchors=['top', 'bottom']),
	'Jcrossedtail': dict(unicode=[0xA7B2], baseGlyphs=['J'], anchors=['top', 'bottom']),

	'Kacute': dict(unicode=[0x1e30], baseGlyphs=['K'], accents=['acute.cap@top']),
	'Kcaron': dict(unicode=[0x1e8], baseGlyphs=['K'], accents=['caron.cap@top']),
	'Kcommaaccent': dict(unicode=[0x136], baseGlyphs=['K'], accents=['commaaccentbelowcmb@bottom']),
	'Kdotbelow': dict(unicode=[0x1e32], baseGlyphs=['K'], accents=['dotbelowcmb@bottom']),
	'Klinebelow': dict(unicode=[0x1e34], baseGlyphs=['K'], accents=['macronbelowcmb@bottom']),
	'Khook': dict(unicode=[0x198], baseGlyphs=['K'], anchors=['top', 'bottom']),
	'Kra': dict(baseGlyphs=['K', 'apostrophemod']),
	

	'Lacute': dict(unicode=[0x139], baseGlyphs=['L'], accents=['acute.cap@top']),
	'Lcaron': dict(unicode=[0x13d], baseGlyphs=['L'], accents=['caroncmb.slovak@topRight']),
	'Lcircumflexbelow': dict(unicode=[0x1e3c], baseGlyphs=['L'], accents=['circumflexbelowcmb@bottom']),
	'Lcommaaccent': dict(unicode=[0x13b], baseGlyphs=['L'], accents=['commaaccentbelowcmb@bottom']),
	'Ldotbelow': dict(unicode=[0x1e36], baseGlyphs=['L'], accents=['dotbelowcmb@bottom']),
	'Ldot': dict(unicode=[0x13f], baseGlyphs=['L'], accents=['dotaccentcmb@middle']),
	'Llinebelow': dict(unicode=[0x1e3a], baseGlyphs=['L'], accents=['macronbelowcmb@bottom']),
	'Lslash': dict(unicode=[0x141], baseGlyphs=['L']),
	'Lstroke': dict(unicode=[0xa748], baseGlyphs=['L'], accents=['overlaystrokeshortcmb@top']),
	'Lbar': dict(unicode=[0x23d], baseGlyphs=['L'], accents=['overlaystrokeshortcmb@middle']),
	'Lbelt': dict(unicode=[0xa7ad], baseGlyphs=['L'], anchors=['top', 'bottom', 'caron']),
	'Lmiddletilde': dict(unicode=[0x2c62], baseGlyphs=['L'], accents=['tildecmb@middle'], anchors=['top', 'bottom', 'caron']),
	'LJ': dict(unicode=[0x01c7], baseGlyphs=['L', 'J']),
	'Lj': dict(unicode=[0x01c8], baseGlyphs=['L', 'j']),

	'Macute': dict(unicode=[0x1e3e], baseGlyphs=['M'], accents=['acute.cap@top']),

	'Nacute': dict(unicode=[0x143], baseGlyphs=['N'], accents=['acute.cap@top']),
	'Ncaron': dict(unicode=[0x147], baseGlyphs=['N'], accents=['caron.cap@top']),
	'Ncircumflexbelow': dict(unicode=[0x1e4a], baseGlyphs=['N'], accents=['circumflexbelowcmb@bottom']),
	'Ncommaaccent': dict(unicode=[0x145], baseGlyphs=['N'], accents=['commaaccentbelowcmb@bottom']),
	'Ndot': dict(unicode=[0x1e44], baseGlyphs=['N'], accents=['dotaccent.cap@top']),
	'Ndotbelow': dict(unicode=[0x1e46], baseGlyphs=['N'], accents=['dotbelowcmb@bottom']),
	'Ngrave': dict(unicode=[0x1f8], baseGlyphs=['N'], accents=['grave.cap@top']),
	'Ntilde': dict(unicode=[0xd1], baseGlyphs=['N'], accents=['tilde.cap@top']),
	'Nlinebelow': dict(unicode=[0x1e48], baseGlyphs=['N'], accents=['macronbelowcmb@bottom']),
	'Nhookleft': dict(unicode=[0x19d], baseGlyphs=['N'], anchors=['top', 'bottom']),
	'Eng': dict(unicode=[0x14a], baseGlyphs=['N'], anchors=['top', 'bottom']),
	'Eng.locl': dict(anchors=['top', 'bottom']),
	'NJ': dict(unicode=[0x1ca], baseGlyphs=['N', 'J']),	# CHECK unicode
	'Nj': dict(unicode=[0x01cb], baseGlyphs=['N', 'j']),

	'Oacute': dict(unicode=[0xd3], baseGlyphs=['O'], accents=['acute.cap@top']),
	'Obreve': dict(unicode=[0x14e], baseGlyphs=['O'], accents=['breve.cap@top']),
	'Ocaron': dict(unicode=[0x1d1], baseGlyphs=['O'], accents=['caron.cap@top']),
	'Ocircumflex': dict(unicode=[0xd4], baseGlyphs=['O'], accents=['circumflex.cap@top']),
	'Ocircumflexacute': dict(unicode=[0x1ed0], baseGlyphs=['O'], accents=['circumflexacute.cap@top']),
	'Ocircumflexdotbelow': dict(unicode=[0x1ed8], baseGlyphs=['O'], accents=['circumflex.cap@top', 'dotbelowcmb@bottom']),
	'Ocircumflexgrave': dict(unicode=[0x1ed2], baseGlyphs=['O'], accents=['circumflexgrave.cap@top']),
	'Ocircumflexhookabove': dict(unicode=[0x1ed4], baseGlyphs=['O'], accents=['circumflexhook.cap@top']),
	'Ocircumflextilde': dict(unicode=[0x1ed6], baseGlyphs=['O'], accents=['circumflextilde.cap@top']),
	'Odieresis': dict(unicode=[0xd6], baseGlyphs=['O'], accents=['dieresis.cap@top']),
	'Odot': dict(unicode=[0x22e], baseGlyphs=['O'], accents=['dotaccent.cap@top']),
	'Odotbelow': dict(unicode=[0x1ecc], baseGlyphs=['O'], accents=['dotbelowcmb@bottom']),
	'Ograve': dict(unicode=[0xd2], baseGlyphs=['O'], accents=['grave.cap@top']),
	'Ohookabove': dict(unicode=[0x1ece], baseGlyphs=['O'], accents=['hookabove.cap@top']),
	'Ohorn': dict(unicode=[0x1a0], baseGlyphs=['O'], accents=['horncmb@horn'], anchors=['top', 'bottom']),
	'Ohornacute': dict(unicode=[0x1eda], baseGlyphs=['Ohorn'], accents=['acute.cap@top']),
	'Ohorndotbelow': dict(unicode=[0x1ee2], baseGlyphs=['Ohorn'], accents=['dotbelowcmb@bottom']),
	'Ohorngrave': dict(unicode=[0x1edc], baseGlyphs=['Ohorn'], accents=['grave.cap@top']),
	'Ohornhookabove': dict(unicode=[0x1ede], baseGlyphs=['Ohorn'], accents=['hookabove.cap@top']),
	'Ohorntilde': dict(unicode=[0x1ee0], baseGlyphs=['Ohorn'], accents=['tilde.cap@top']),
	'Ohungarumlaut': dict(unicode=[0x150], baseGlyphs=['O'], accents=['hungarumlaut.cap@top']),
	'Omacron': dict(unicode=[0x14c], baseGlyphs=['O'], accents=['macron.cap@top']),
	'Oogonek': dict(unicode=[0x1ea], baseGlyphs=['O'], accents=['ogonekcmb@ogonek'], anchors=['top', 'bottom']),
	'Oslash': dict(unicode=[0xd8], baseGlyphs=['O'], accents=['soliduslongoverlaycmb.cap@middle'], anchors=['top', 'bottom']),
	'Oslashacute': dict(unicode=[0x1fe], baseGlyphs=['Oslash'], accents=['acute.cap@top']),
	'Otilde': dict(unicode=[0xd5], baseGlyphs=['O'], accents=['tilde.cap@top']),
	'Otildeacute': dict(unicode=[0x1e4c], baseGlyphs=['O'], accents=['tildeacute.cap@top']),
	'Obar': dict(unicode=[0x19f], baseGlyphs=['O'], anchors=['top', 'bottom', 'ogonek']),
	'Oopen': dict(unicode=[0x186], anchors=['top', 'bottom']),
	'OE': dict(unicode=[0x152], baseGlyphs=['O','E'], anchors=['top', 'bottom']),

	'Pdotaccent': dict(unicode=[0x1E56], baseGlyphs=['P'], accents=['dotaccent.cap@top']),
	'Phook': dict(unicode=[0x1a4], baseGlyphs=['P'], anchors=['top', 'bottom']),
	'Pstroke': dict(unicode=[0x2C63], baseGlyphs=['P'], accents=['overlaystrokeshortcmb@middle'], anchors=['top', 'bottom']),
	'Thorn': dict(unicode=[0x00DE], baseGlyphs=['P'], anchors=['top', 'bottom']),

	'Racute': dict(unicode=[0x154], baseGlyphs=['R'], accents=['acute.cap@top']),
	'Rcaron': dict(unicode=[0x158], baseGlyphs=['R'], accents=['caron.cap@top']),
	'Rcommaaccent': dict(unicode=[0x156], baseGlyphs=['R'], accents=['commaaccentbelowcmb@bottom']),
	'Rdotbelow': dict(unicode=[0x1e5a], baseGlyphs=['R'], accents=['dotbelowcmb@bottom']),
	'Rlinebelow': dict(unicode=[0x1E5E], baseGlyphs=['R'], accents=['macronbelowcmb@bottom']),
	'Rstroke': dict(unicode=[0x24c], baseGlyphs=['R'], accents=['overlaystrokeshortcmb@middle'], anchors=['top', 'bottom']),
	'Rtail': dict(unicode=[0x2c64], baseGlyphs=['R'], anchors=['top', 'bottom']),
	'yr': dict(unicode=[0x01A6], baseGlyphs=['R'], anchors=['top', 'bottom']),

	'Sacute': dict(unicode=[0x15a], baseGlyphs=['S'], accents=['acute.cap@top']),
	'Scaron': dict(unicode=[0x160], baseGlyphs=['S'], accents=['caron.cap@top']),
	'Scedilla': dict(unicode=[0x15e], baseGlyphs=['S'], accents=['cedillacmb@bottom']),
	'Scircumflex': dict(unicode=[0x15c], baseGlyphs=['S'], accents=['circumflex.cap@top']),
	'Scommaaccent': dict(unicode=[0x218], baseGlyphs=['S'], accents=['commaaccentbelowcmb@bottom']),
	'Sdotbelow': dict(unicode=[0x1e62], baseGlyphs=['S'], accents=['dotbelowcmb@bottom']),
	'Germandbls': dict(unicode=[0x1e9e]),
	'Esh': dict(unicode=[0x1a9], anchors=['top', 'bottom']),

	'Tbar': dict(unicode=[0x166], baseGlyphs=['T'], accents=['overlaystrokeshortcmb@middle'], anchors=['top', 'bottom']),
	'Tcaron': dict(unicode=[0x164], baseGlyphs=['T'], accents=['caron.cap@top']),
	'Tcedilla': dict(unicode=[0x162], baseGlyphs=['T'], accents=['cedillacmb@bottom']),
	'Tcircumflexbelow': dict(unicode=[0x1e70], baseGlyphs=['T'], accents=['circumflexbelowcmb@bottom']),
	'Tcommaaccent': dict(unicode=[0x21a], baseGlyphs=['T'], accents=['commaaccentbelowcmb@bottom']),
	'Tdotbelow': dict(unicode=[0x1e6c], baseGlyphs=['T'], accents=['dotbelowcmb@bottom']),
	'Tlinebelow': dict(unicode=[0x1e6e], baseGlyphs=['T'], accents=['macronbelowcmb@bottom']),
	'Twithdiagonalstroke': dict(unicode=[0x23e], baseGlyphs=['T'], accents=['soliduslongoverlaycmb.cap@middle']),
	'Thook': dict(unicode=[0x1ac], baseGlyphs=['T'], anchors=['top', 'bottom']),
	'Tretroflexhook': dict(unicode=[0x01AE], baseGlyphs=['T'], anchors=['top']),
	'Theta.LATN': dict(unicode=[0x0398], anchors=['top', 'bottom']),

	'Uacute': dict(unicode=[0xda], baseGlyphs=['U'], accents=['acute.cap@top']),
	'Ubreve': dict(unicode=[0x16c], baseGlyphs=['U'], accents=['breve.cap@top']),
	'Ucaron': dict(unicode=[0x1d3], baseGlyphs=['U'], accents=['caron.cap@top']),
	'Ucircumflex': dict(unicode=[0xdb], baseGlyphs=['U'], accents=['circumflex.cap@top']),
	'Udieresis': dict(unicode=[0xdc], baseGlyphs=['U'], accents=['dieresis.cap@top']),
	'Udieresisacute': dict(unicode=[0x1d7], baseGlyphs=['U'], accents=['dieresisacute.cap@top']),
	'Udieresiscaron': dict(unicode=[0x1d9], baseGlyphs=['U'], accents=['dieresiscaron.cap@top']),
	'Udieresisgrave': dict(unicode=[0x1db], baseGlyphs=['U'], accents=['dieresisgrave.cap@top']),
	'Udieresismacron': dict(unicode=[0x1d5], baseGlyphs=['U'], accents=['dieresismacron.cap@top']),
	'Udotbelow': dict(unicode=[0x1ee4], baseGlyphs=['U'], accents=['dotbelowcmb@bottom']),
	'Ugrave': dict(unicode=[0xd9], baseGlyphs=['U'], accents=['grave.cap@top']),
	'Uhookabove': dict(unicode=[0x1ee6], baseGlyphs=['U'], accents=['hookabove.cap@top']),
	'Uhorn': dict(unicode=[0x1af], baseGlyphs=['U'], accents=['horncmb@horn'], anchors=['top', 'bottom']),
	'Uhornacute': dict(unicode=[0x1ee8], baseGlyphs=['Uhorn'], accents=['acute.cap@top']),
	'Uhorndotbelow': dict(unicode=[0x1ef0], baseGlyphs=['Uhorn'], accents=['dotbelowcmb@bottom']),
	'Uhorngrave': dict(unicode=[0x1eea], baseGlyphs=['Uhorn'], accents=['grave.cap@top']),
	'Uhornhookabove': dict(unicode=[0x1eec], baseGlyphs=['Uhorn'], accents=['hookabove.cap@top']),
	'Uhorntilde': dict(unicode=[0x1eee], baseGlyphs=['Uhorn'], accents=['tilde.cap@top']),
	'Uhungarumlaut': dict(unicode=[0x170], baseGlyphs=['U'], accents=['hungarumlaut.cap@top']),
	'Umacron': dict(unicode=[0x16a], baseGlyphs=['U'], accents=['macron.cap@top']),
	'Uogonek': dict(unicode=[0x172], baseGlyphs=['U'], accents=['ogonekcmb@ogonek']),
	'Uogonek.NAV': dict(baseGlyphs=['U'], accents=['ogonekcmb.NAV@bottom']),
	'Uring': dict(unicode=[0x16e], baseGlyphs=['U'], accents=['ring.cap@top']),
	'Utilde': dict(unicode=[0x168], baseGlyphs=['U'], accents=['tilde.cap@top']),
	'Utildeacute': dict(unicode=[0x1e78], baseGlyphs=['U'], accents=['tildeacute.cap@top']),
	'Utildebelow': dict(unicode=[0x1E74], baseGlyphs=['U'], accents=['tildebelowcmb@bottom']),
	'Ubar': dict(unicode=[0x244], baseGlyphs=['U'], anchors=['top', 'bottom']),
	'Ustroke': dict(unicode=[0xa7b8], baseGlyphs=['U'], accents=['soliduslongoverlaycmb.cap@middle'], anchors=['top', 'bottom']),

	'Vhook': dict(unicode=[0x1b2], anchors=['top', 'bottom', 'topRight']),
	'Upsilon.LATN': dict(unicode=[0x1b1], anchors=['top', 'bottom']),
	'Vturned': dict(unicode=[0x245], baseGlyphs=['V'], anchors=['top', 'bottom']),
	'Vtilde': dict(unicode=[0x1e7c], baseGlyphs=['V'], accents=['tilde.cap@top']),

	'Wacute': dict(unicode=[0x1e82], baseGlyphs=['W'], accents=['acute.cap@top']),
	'Wcircumflex': dict(unicode=[0x174], baseGlyphs=['W'], accents=['circumflex.cap@top']),
	'Wdieresis': dict(unicode=[0x1e84], baseGlyphs=['W'], accents=['dieresis.cap@top']),
	'Wgrave': dict(unicode=[0x1e80], baseGlyphs=['W'], accents=['grave.cap@top']),
	'Whook': dict(unicode=[0x2c72], baseGlyphs=['W'], anchors=['top', 'bottom']),

	'Xdieresis': dict(unicode=[0x1e8c], baseGlyphs=['X'], accents=['dieresis.cap@top']),
	'Xdot': dict(unicode=[0x1e8a], baseGlyphs=['X'], accents=['dotaccent.cap@top']),
	'Chi.LATN': dict(unicode=[0xA7B3], anchors=['top', 'bottom']),

	'Yacute': dict(unicode=[0xdd], baseGlyphs=['Y'], accents=['acute.cap@top']),
	'Ycircumflex': dict(unicode=[0x176], baseGlyphs=['Y'], accents=['circumflex.cap@top']),
	'Ydieresis': dict(unicode=[0x178], baseGlyphs=['Y'], accents=['dieresis.cap@top']),
	'Ydotbelow': dict(unicode=[0x1ef4], baseGlyphs=['Y'], accents=['dotbelowcmb@bottom']),
	'Ygrave': dict(unicode=[0x1ef2], baseGlyphs=['Y'], accents=['grave.cap@top']),
	'Yhookabove': dict(unicode=[0x1ef6], baseGlyphs=['Y'], accents=['hookabove.cap@top']),
	'Ymacron': dict(unicode=[0x232], baseGlyphs=['Y'], accents=['macron.cap@top']),
	'Ytilde': dict(unicode=[0x1ef8], baseGlyphs=['Y'], accents=['tilde.cap@top']),
	'Yturnedsans': dict(unicode=[0x2144], baseGlyphs=['Y'], anchors=['top', 'bottom']),
	'Yhook': dict(unicode=[0x1b3], baseGlyphs=['Y'], anchors=['top', 'bottom']),

	'Zacute': dict(unicode=[0x179], baseGlyphs=['Z'], accents=['acute.cap@top']),
	'Zcaron': dict(unicode=[0x17d], baseGlyphs=['Z'], accents=['caron.cap@top']),
	'Zdotaccent': dict(unicode=[0x17b], baseGlyphs=['Z'], accents=['dotaccent.cap@top']),
	'Zcircumflex': dict(unicode=[0x1e90], baseGlyphs=['Z'], accents=['circumflex.cap@top']),
	'Zdotbelow': dict(unicode=[0x1e92], baseGlyphs=['Z'], accents=['dotbelowcmb@bottom']),
	'Zstroke': dict(unicode=[0x1b5], baseGlyphs=['Z'], accents=['overlaystrokeshortcmb@middle']),
	
	'Ezh': dict(unicode=[0x1b7], anchors=['top', 'bottom']),
	'Ezhcaron': dict(unicode=[0x1ee], baseGlyphs=['Ezh'], accents=['caron.cap@top']),
	'Gamma.LATN': dict(unicode=[0x194], anchors=['top', 'bottom']),
	'Glottalstop': dict(unicode=[0x0241], anchors=['top', 'bottom']),
	'Saltillo': dict(unicode=[0xA78B]),

	'aacute': dict(unicode=[0xe1], baseGlyphs=['a'], accents=['acutecmb@top'], anchors=['top', 'bottom']),
	'abreve': dict(unicode=[0x103], baseGlyphs=['a'], accents=['brevecmb@top'], anchors=['top', 'bottom']),
	'abreveacute': dict(unicode=[0x1eaf], baseGlyphs=['a'], accents=['breveacutecmb@top'], anchors=['top', 'bottom']),
	'abrevedotbelow': dict(unicode=[0x1eb7], baseGlyphs=['a'], accents=['brevecmb@top', 'dotbelowcmb@bottom'], anchors=['top', 'bottom']),
	'abrevegrave': dict(unicode=[0x1eb1], baseGlyphs=['a'], accents=['brevegravecmb@top'], anchors=['top', 'bottom']),
	'abrevetilde': dict(unicode=[0x1eb5], baseGlyphs=['a'], accents=['brevetildecmb@top'], anchors=['top', 'bottom']),
	'abrevehookabove': dict(unicode=[0x1eb3], baseGlyphs=['a'], accents=['brevehookcmb@top'], anchors=['top', 'bottom']),
	'acaron': dict(unicode=[0x1ce], baseGlyphs=['a'], accents=['caroncmb@top'], anchors=['top', 'bottom']),
	'acircumflex': dict(unicode=[0xe2], baseGlyphs=['a'], accents=['circumflexcmb@top'], anchors=['top', 'bottom']),
	'acircumflexacute': dict(unicode=[0x1ea5], baseGlyphs=['a'], accents=['circumflexacutecmb@top'], anchors=['top', 'bottom']),
	'acircumflexdotbelow': dict(unicode=[0x1ead], baseGlyphs=['a'], accents=['circumflexcmb@top', 'dotbelowcmb@bottom'], anchors=['top', 'bottom']),
	'acircumflexgrave': dict(unicode=[0x1ea7], baseGlyphs=['a'], accents=['circumflexgravecmb@top'], anchors=['top', 'bottom']),
	'acircumflexhookabove': dict(unicode=[0x1ea9], baseGlyphs=['a'], accents=['circumflexhookcmb@top'], anchors=['top', 'bottom']),
	'acircumflextilde': dict(unicode=[0x1eab], baseGlyphs=['a'], accents=['circumflextildecmb@top'], anchors=['top', 'bottom']),
	'adieresis': dict(unicode=[0xe4], baseGlyphs=['a'], accents=['dieresiscmb@top'], anchors=['top', 'bottom']),
	'adieresismacron': dict(unicode=[0x1df], baseGlyphs=['a'], accents=['dieresismacroncmb@top'], anchors=['top', 'bottom']),
	'adot': dict(unicode=[0x227], baseGlyphs=['a'], accents=['dotaccentcmb@top'], anchors=['top', 'bottom']),
	'adotbelow': dict(unicode=[0x1ea1], baseGlyphs=['a'], accents=['dotbelowcmb@bottom'], anchors=['top', 'bottom']),
	'agrave': dict(unicode=[0xe0], baseGlyphs=['a'], accents=['gravecmb@top'], anchors=['top', 'bottom']),
	'ahookabove': dict(unicode=[0x1ea3], baseGlyphs=['a'], accents=['hookabovecmb@top'], anchors=['top', 'bottom']),
	'amacron': dict(unicode=[0x101], baseGlyphs=['a'], accents=['macroncmb@top'], anchors=['top', 'bottom']),
	'aogonek': dict(unicode=[0x105], baseGlyphs=['a'], accents=['ogonekcmb@ogonek'], anchors=['top', 'bottom']),
	'aogonek.NAV': dict(baseGlyphs=['a'], accents=['ogonekcmb.NAV@bottom'], anchors=['top', 'bottom']),
	'aring': dict(unicode=[0xe5], baseGlyphs=['a'], accents=['ringabovecmb@top'], anchors=['top', 'bottom']),
	'aringacute': dict(unicode=[0x1fb], baseGlyphs=['a'], accents=['ringacutecmb@top'], anchors=['top', 'bottom']),
	'atilde': dict(unicode=[0xe3], baseGlyphs=['a'], accents=['tildecmb@top'], anchors=['top', 'bottom']),
	'astroke': dict(unicode=[0x2c65], baseGlyphs=['a'], accents=['soliduslongoverlaycmb@middle'], anchors=['top', 'bottom']),
	'alpha.IPA': dict(unicode=[0x251], anchors=['bottom', 'top']),
	'acircle': dict(unicode=[0x24d0], baseGlyphs=['at'], anchors=['top', 'bottom']),
	
	'ae': dict(unicode=[0xe6], baseGlyphs=['a','e'], anchors=['top', 'bottom']),
	'aeacute': dict(unicode=[0x1fd], baseGlyphs=['ae'], accents=['acutecmb@top'], anchors=['top', 'bottom']),

	'bdotbelow': dict(unicode=[0x1e05], baseGlyphs=['b'], accents=['dotbelowcmb@bottom'], anchors=['top', 'bottom']),
	'blinebelow': dict(unicode=[0x1e07], baseGlyphs=['b'], accents=['macronbelowcmb@bottom'], anchors=['top', 'bottom']),
	'bhook': dict(unicode=[0x253], baseGlyphs=['b'], anchors=['top', 'bottom']),

	'cacute': dict(unicode=[0x107], baseGlyphs=['c'], accents=['acutecmb@top'], anchors=['top', 'bottom']),
	'ccaron': dict(unicode=[0x10d], baseGlyphs=['c'], accents=['caroncmb@top'], anchors=['top', 'bottom']),
	'ccedilla': dict(unicode=[0xe7], baseGlyphs=['c'], accents=['cedillacmb@bottom'], anchors=['top', 'bottom']),
	'ccircumflex': dict(unicode=[0x109], baseGlyphs=['c'], accents=['circumflexcmb@top'], anchors=['top', 'bottom']),
	'cdotaccent': dict(unicode=[0x10b], baseGlyphs=['c'], accents=['dotaccentcmb@top'], anchors=['top', 'bottom']),
	'cstroke': dict(unicode=[0x23c], baseGlyphs=['c'], accents=['soliduslongoverlaycmb@middle'], anchors=['top', 'bottom']),
	'chook': dict(unicode=[0x188], baseGlyphs=['c'], anchors=['top', 'bottom']),

	'dcaron': dict(unicode=[0x10f], baseGlyphs=['d'], accents=['caroncmb.slovak@topRight'], anchors=['top', 'bottom']),
	'dcircumflexbelow': dict(unicode=[0x1e13], baseGlyphs=['d'], accents=['circumflexbelowcmb@bottom'], anchors=['top', 'bottom']),
	'ddotbelow': dict(unicode=[0x1e0d], baseGlyphs=['d'], accents=['dotbelowcmb@bottom'], anchors=['top', 'bottom']),
	'dcommaaccent': dict(unicode=[0x1e11], baseGlyphs=['d'], accents=['commaaccentbelowcmb@bottom'], anchors=['top', 'bottom']),
	'dlinebelow': dict(unicode=[0x1e0f], baseGlyphs=['d'], accents=['macronbelowcmb@bottom'], anchors=['top', 'bottom']),
	'dhook': dict(unicode=[0x257], baseGlyphs=['d'], anchors=['top', 'bottom']),
	'dtail': dict(unicode=[0x256], baseGlyphs=['d'], anchors=['topRight', 'top', 'bottom']),
	'dcroat': dict(unicode=[0x111], baseGlyphs=['d'], accents=['overlaystrokeshortcmb@middle'], anchors=['top', 'bottom']),
	'dstroke': dict(unicode=[0xa7c8], baseGlyphs=['d'], accents=['overlaystrokeshortcmb@middle'], anchors=['top', 'bottom']),
	'dzcaron': dict(unicode=[0x01c6], baseGlyphs=['d', 'zcaron']),

	'eth': dict(unicode=[0xf0], anchors=['top', 'bottom']),
	'eacute': dict(unicode=[0xe9], baseGlyphs=['e'], accents=['acutecmb@top'], anchors=['top', 'bottom']),
	'ebreve': dict(unicode=[0x115], baseGlyphs=['e'], accents=['brevecmb@top'], anchors=['top', 'bottom']),
	'ecaron': dict(unicode=[0x11b], baseGlyphs=['e'], accents=['caroncmb@top'], anchors=['top', 'bottom']),
	'ecedilla': dict(unicode=[0x229], baseGlyphs=['e'], accents=['cedillacmb@bottom'], anchors=['top', 'bottom']),
	'ecircumflex': dict(unicode=[0xea], baseGlyphs=['e'], accents=['circumflexcmb@top'], anchors=['top', 'bottom']),
	'ecircumflexacute': dict(unicode=[0x1ebf], baseGlyphs=['e'], accents=['circumflexacutecmb@top'], anchors=['top', 'bottom']),
	'ecircumflexdotbelow': dict(unicode=[0x1ec7], baseGlyphs=['e'], accents=['circumflexcmb@top', 'dotbelowcmb@bottom'], anchors=['top', 'bottom']),
	'ecircumflexgrave': dict(unicode=[0x1ec1], baseGlyphs=['e'], accents=['circumflexgravecmb@top'], anchors=['top', 'bottom']),
	'ecircumflexhookabove': dict(unicode=[0x1ec3], baseGlyphs=['e'], accents=['circumflexhookcmb@top'], anchors=['top', 'bottom']),
	'ecircumflextilde': dict(unicode=[0x1ec5], baseGlyphs=['e'], accents=['circumflextildecmb@top'], anchors=['top', 'bottom']),
	'edieresis': dict(unicode=[0xeb], baseGlyphs=['e'], accents=['dieresiscmb@top'], anchors=['top', 'bottom']),
	'edotaccent': dict(unicode=[0x117], baseGlyphs=['e'], accents=['dotaccentcmb@top'], anchors=['top', 'bottom']),
	'edotbelow': dict(unicode=[0x1eb9], baseGlyphs=['e'], accents=['dotbelowcmb@bottom'], anchors=['top', 'bottom']),
	'egrave': dict(unicode=[0xe8], baseGlyphs=['e'], accents=['gravecmb@top'], anchors=['top', 'bottom']),
	'ehookabove': dict(unicode=[0x1ebb], baseGlyphs=['e'], accents=['hookabovecmb@top'], anchors=['top', 'bottom']),
	'emacron': dict(unicode=[0x113], baseGlyphs=['e'], accents=['macroncmb@top'], anchors=['top', 'bottom']),
	'eogonek': dict(unicode=[0x119], baseGlyphs=['e'], accents=['ogonekcmb@ogonek'], anchors=['top', 'bottom']),
	'eogonek.NAV': dict(baseGlyphs=['e'], accents=['ogonekcmb.NAV@bottom'], anchors=['top', 'bottom']),
	'estroke': dict(unicode=[0x247], baseGlyphs=['e'], accents=['soliduslongoverlaycmb@middle'], anchors=['top', 'bottom']),
	'etilde': dict(unicode=[0x1ebd], baseGlyphs=['e'], accents=['tildecmb@top'], anchors=['top', 'bottom']),
	'etildebelow': dict(unicode=[0x1e1b], baseGlyphs=['e'], accents=['tildebelowcmb@bottom'], anchors=['top', 'bottom']),
	#'eturned': dict(unicode=[0x01DD], baseGlyphs=['schwa'], anchors=['top', 'bottom']),
	'schwa': dict(unicode=[0x259, 0x01DD], anchors=['top', 'bottom', 'topRight']),
	'eopen': dict(unicode=[0x25b], anchors=['top', 'bottom']),

	'fhook': dict(unicode=[0x192], baseGlyphs=['f'], anchors=['top', 'bottom']),

	'gacute': dict(unicode=[0x1f5], baseGlyphs=['g'], accents=['acutecmb@top'], anchors=['top', 'bottom']),
	'gbreve': dict(unicode=[0x11f], baseGlyphs=['g'], accents=['brevecmb@top'], anchors=['top', 'bottom']),
	'gcaron': dict(unicode=[0x1e7], baseGlyphs=['g'], accents=['caroncmb@top'], anchors=['top', 'bottom']),
	'gcircumflex': dict(unicode=[0x11d], baseGlyphs=['g'], accents=['circumflexcmb@top'], anchors=['top', 'bottom']),
	'gcommaaccent': dict(unicode=[0x123], baseGlyphs=['g'], accents=['revcommaaccentcmb@top'], anchors=['top', 'bottom']),
	'gdotaccent': dict(unicode=[0x121], baseGlyphs=['g'], accents=['dotaccentcmb@top'], anchors=['top', 'bottom']),
	'gstroke': dict(unicode=[0x1e5], baseGlyphs=['g'], accents=['overlaystrokeshortcmb@middle'], anchors=['top']),
	'gscript.IPA': dict(unicode=[0x261], anchors=['top', 'bottom', 'topRight']),
	'ghook': dict(unicode=[0x260], baseGlyphs=['g'], anchors=['top']),

	'hcaron': dict(unicode=[0x21f], baseGlyphs=['h'], accents=['caron.cap@top']),
	'hcircumflex': dict(unicode=[0x125], baseGlyphs=['h'], accents=['circumflex.cap@top']),
	'hdieresis': dict(unicode=[0x1e27], baseGlyphs=['h'], accents=['dieresis.cap@top']),
	'hdotbelow': dict(unicode=[0x1e25], baseGlyphs=['h'], accents=['dotbelowcmb@bottom']),
	'hbar': dict(unicode=[0x127], baseGlyphs=['h'], accents=['overlaystrokeshortcmb@middle'], anchors=['top', 'bottom']),
	'hhook': dict(unicode=[0x266], baseGlyphs=['h'], anchors=['top', 'bottom']),
	'hturned': dict(unicode=[0x0265], baseGlyphs=['h'], anchors=['top', 'bottom']),

	'dotlessi': dict(unicode=[0x131], anchors=['bottom', 'top', 'ogonek', 'middle']),
	'iacute': dict(unicode=[0xed], baseGlyphs=['dotlessi'], accents=['acutecmb@top']),
	'ibreve': dict(unicode=[0x12d], baseGlyphs=['dotlessi'], accents=['brevecmb@top']),
	'icaron': dict(unicode=[0x1d0], baseGlyphs=['dotlessi'], accents=['caroncmb@top']),
	'icircumflex': dict(unicode=[0xee], baseGlyphs=['dotlessi'], accents=['circumflexcmb@top']),
	'idieresis': dict(unicode=[0xef], baseGlyphs=['dotlessi'], accents=['dieresiscmb@top']),
	'idotaccent': dict(baseGlyphs=['dotlessi'], accents=['dotaccentcmb@top']),
	'idotbelow': dict(unicode=[0x1ecb], baseGlyphs=['i'], accents=['dotbelowcmb@bottom']),
	'igrave': dict(unicode=[0xec], baseGlyphs=['dotlessi'], accents=['gravecmb@top']),
	'ihookabove': dict(unicode=[0x1ec9], baseGlyphs=['dotlessi'], accents=['hookabovecmb@top']),
	'imacron': dict(unicode=[0x12b], baseGlyphs=['dotlessi'], accents=['macroncmb@top']),
	'iogonek': dict(unicode=[0x12f], baseGlyphs=['i'], accents=['ogonekcmb@ogonek']),
	'dotlessiogonek': dict(baseGlyphs=['dotlessi'], accents=['ogonekcmb@ogonek'], anchors=['top']),
	'istroke': dict(unicode=[0x268], baseGlyphs=['dotlessistroke'], accents=['dotaccentcmb@top']),
	'dotlessistroke': dict(anchors=['bottom', 'top'], baseGlyphs=['dotlessi'], accents=['overlaystrokeshortcmb@middle']),
	'itilde': dict(unicode=[0x129], baseGlyphs=['dotlessi'], accents=['tildecmb@top']),
	'itildebelow': dict(unicode=[0x1e2d], baseGlyphs=['i'], accents=['tildebelowcmb@bottom']),
	'Ismall.IPA': dict(unicode=[0x26a], anchors=['top', 'bottom']),
	'iota.IPA': dict(unicode=[0x269], anchors=['bottom', 'top']),
	'ij': dict(unicode=[0x133], baseGlyphs=['i', 'j']),
	'ijacute': dict(baseGlyphs=['iacute', 'dotlessj', 'acutecmb']),

	'dotlessj': dict(unicode=[0x237], baseGlyphs=['j'],anchors=['top', 'middle']),
	'jcaron': dict(unicode=[0x1f0], baseGlyphs=['dotlessj'], accents=['caroncmb@top']),
	'jcircumflex': dict(unicode=[0x135], baseGlyphs=['dotlessj'], accents=['circumflexcmb@top']),
	'jstroke': dict(unicode=[0x249], baseGlyphs=['j'], accents=['overlaystrokeshortcmb@middle'], anchors=['top', 'bottom']),
	'jcrossedtail': dict(unicode=[0x029D], baseGlyphs=['j'], anchors=['top', 'bottom']),

	'kacute': dict(unicode=[0x1e31], baseGlyphs=['k'], accents=['acute.cap@top']),
	'kcaron': dict(unicode=[0x1e9], baseGlyphs=['k'], accents=['caron.cap@top']),
	'kcommaaccent': dict(unicode=[0x137], baseGlyphs=['k'], accents=['commaaccentbelowcmb@bottom']),
	'kdotbelow': dict(unicode=[0x1e33], baseGlyphs=['k'], accents=['dotbelowcmb@bottom']),
	'klinebelow': dict(unicode=[0x1e35], baseGlyphs=['k'], accents=['macronbelowcmb@bottom']),
	'kra': dict(unicode=[0x0138], anchors=['top', 'bottom']),
	'khook': dict(unicode=[0x199], baseGlyphs=['k'], anchors=['top', 'bottom']),

	'lacute': dict(unicode=[0x13a], baseGlyphs=['l'], accents=['acute.cap@top']),
	'lcaron': dict(unicode=[0x13e], baseGlyphs=['l'], accents=['caroncmb.slovak@topRight']),
	'lcircumflexbelow': dict(unicode=[0x1e3d], baseGlyphs=['l'], accents=['circumflexbelowcmb@bottom']),
	'lcommaaccent': dict(unicode=[0x13c], baseGlyphs=['l'], accents=['commaaccentbelowcmb@bottom']),
	'ldotbelow': dict(unicode=[0x1e37], baseGlyphs=['l'], accents=['dotbelowcmb@bottom']),
	'ldot': dict(unicode=[0x140], baseGlyphs=['l'], accents=['dotaccentcmb@middle']), 
	'llinebelow': dict(unicode=[0x1e3b], baseGlyphs=['l'], accents=['macronbelowcmb@bottom']),
	'lslash': dict(unicode=[0x142], baseGlyphs=['l']),
	'lstroke': dict(unicode=[0xa749], baseGlyphs=['l'], accents=['overlaystrokeshortcmb@middle']),
	'lbar': dict(unicode=[0x19a], baseGlyphs=['l'], accents=['overlaystrokeshortcmb@middle'], anchors=['bottom', 'top']),
	'lbelt': dict(unicode=[0x26c], baseGlyphs=['l'], anchors=['bottom', 'top']),
	'lmiddletilde': dict(unicode=[0x26b], baseGlyphs=['l'], accents=['tildecmb@middle'], anchors=['caron', 'bottom', 'top']),
	'lj': dict(unicode=[0x01c9], baseGlyphs=['l', 'j']),

	'macute': dict(unicode=[0x1e3f], baseGlyphs=['m'], accents=['acutecmb@top']),

	'nacute': dict(unicode=[0x144], baseGlyphs=['n'], accents=['acutecmb@top']),
	'ncaron': dict(unicode=[0x148], baseGlyphs=['n'], accents=['caroncmb@top']),
	'ncircumflexbelow': dict(unicode=[0x1e4b], baseGlyphs=['n'], accents=['circumflexbelowcmb@bottom']),
	'ngrave': dict(unicode=[0x1f9], baseGlyphs=['n'], accents=['gravecmb@top']),
	'ncommaaccent': dict(unicode=[0x146], baseGlyphs=['n'], accents=['commaaccentbelowcmb@bottom']),
	'ndot': dict(unicode=[0x1e45], baseGlyphs=['n'], accents=['dotaccentcmb@top']),
	'ndotbelow': dict(unicode=[0x1e47], baseGlyphs=['n'], accents=['dotbelowcmb@bottom']),
	'nlinebelow': dict(unicode=[0x1e49], baseGlyphs=['n'], accents=['macronbelowcmb@bottom']),
	'ntilde': dict(unicode=[0xf1], baseGlyphs=['n'], accents=['tildecmb@top']),
	'nhookleft': dict(unicode=[0x272], baseGlyphs=['n'], anchors=['top', 'bottom','topRight']),
	'eng': dict(unicode=[0x14b], baseGlyphs=['n'], anchors=['top', 'bottom','topRight']),
	'nj': dict(unicode=[0x1cc], baseGlyphs=['n', 'j']),

	'oacute': dict(unicode=[0xf3], baseGlyphs=['o'], accents=['acutecmb@top']),
	'obreve': dict(unicode=[0x14f], baseGlyphs=['o'], accents=['brevecmb@top']),
	'ocaron': dict(unicode=[0x1d2], baseGlyphs=['o'], accents=['caroncmb@top']),
	'ocircumflex': dict(unicode=[0xf4], baseGlyphs=['o'], accents=['circumflexcmb@top']),
	'ocircumflexacute': dict(unicode=[0x1ed1], baseGlyphs=['o'], accents=['circumflexacutecmb@top']),
	'ocircumflexdotbelow': dict(unicode=[0x1ed9], baseGlyphs=['o'], accents=['circumflexcmb@top', 'dotbelowcmb@bottom']),
	'ocircumflexgrave': dict(unicode=[0x1ed3], baseGlyphs=['o'], accents=['circumflexgravecmb@top']),
	'ocircumflexhookabove': dict(unicode=[0x1ed5], baseGlyphs=['o'], accents=['circumflexhookcmb@top']),
	'ocircumflextilde': dict(unicode=[0x1ed7], baseGlyphs=['o'], accents=['circumflextildecmb@top']),
	'odieresis': dict(unicode=[0xf6], baseGlyphs=['o'], accents=['dieresiscmb@top']),
	'odot': dict(unicode=[0x22f], baseGlyphs=['o'], accents=['dotaccentcmb@top']),
	'odotbelow': dict(unicode=[0x1ecd], baseGlyphs=['o'], accents=['dotbelowcmb@bottom']),
	'ograve': dict(unicode=[0xf2], baseGlyphs=['o'], accents=['gravecmb@top']),
	'ohookabove': dict(unicode=[0x1ecf], baseGlyphs=['o'], accents=['hookabovecmb@top']),
	'ohorn': dict(unicode=[0x1a1], baseGlyphs=['o'], accents=['horncmb@horn'], anchors=['bottom', 'top']),
	'ohornacute': dict(unicode=[0x1edb], baseGlyphs=['ohorn'], accents=['acutecmb@top']),
	'ohorndotbelow': dict(unicode=[0x1ee3], baseGlyphs=['ohorn'], accents=['dotbelowcmb@bottom']),
	'ohorngrave': dict(unicode=[0x1edd], baseGlyphs=['ohorn'], accents=['gravecmb@top']),
	'ohornhookabove': dict(unicode=[0x1edf], baseGlyphs=['ohorn'], accents=['hookabovecmb@top']),
	'ohorntilde': dict(unicode=[0x1ee1], baseGlyphs=['ohorn'], accents=['tildecmb@top']),
	'ohungarumlaut': dict(unicode=[0x151], baseGlyphs=['o'], accents=['hungarumlautcmb@top']),
	'omacron': dict(unicode=[0x14d], baseGlyphs=['o'], accents=['macroncmb@top']),
	'oogonek': dict(unicode=[0x1eb], baseGlyphs=['o'], accents=['ogonekcmb@ogonek']),
	'oslash': dict(unicode=[0xf8], baseGlyphs=['o'], accents=['soliduslongoverlaycmb@middle']	, anchors=['top', 'bottom']),
	'oslashacute': dict(unicode=[0x1ff], baseGlyphs=['oslash'], accents=['acutecmb@top']),
	'otilde': dict(unicode=[0xf5], baseGlyphs=['o'], accents=['tildecmb@top']),
	'otildeacute': dict(unicode=[0x1e4d], baseGlyphs=['o'], accents=['tildeacutecmb@top']),
	'oopen': dict(unicode=[0x254], anchors=['top', 'bottom']),
	'obarred': dict(unicode=[0x275], baseGlyphs=['o'], anchors=['top', 'bottom']),
	'oe': dict(unicode=[0x153], baseGlyphs=['o', 'e'], anchors=['top', 'bottom']),

	'pdotaccent': dict(unicode=[0x1E57], baseGlyphs=['p'], accents=['dotaccentcmb@top']),
	'phook': dict(unicode=[0x1a5], baseGlyphs=['p'], anchors=['top', 'bottom']),
	'pstroke': dict(unicode=[0x1D7D], baseGlyphs=['p'], anchors=['top', 'bottom']),
	'thorn': dict(unicode=[0xfe], baseGlyphs=['p'], anchors=['top', 'bottom']),

	'racute': dict(unicode=[0x155], baseGlyphs=['r'], accents=['acutecmb@top']),
	'rcaron': dict(unicode=[0x159], baseGlyphs=['r'], accents=['caroncmb@top']),
	'rcommaaccent': dict(unicode=[0x157], baseGlyphs=['r'], accents=['commaaccentbelowcmb@bottom']),
	'rdotbelow': dict(unicode=[0x1e5b], baseGlyphs=['r'], accents=['dotbelowcmb@bottom']),
	'rlinebelow': dict(unicode=[0x1E5F], baseGlyphs=['r'], accents=['macronbelowcmb@bottom']),
	'rtail.IPA': dict(unicode=[0x27d], baseGlyphs=['r'], anchors=['top', 'bottom']),
	'rstroke': dict(unicode=[0x24d], baseGlyphs=['r'], accents=['overlaystrokeshortcmb@middle'], anchors=['top', 'bottom']),
	'Rsmall': dict(unicode=[0x0280], anchors=['top', 'bottom']),

	'sacute': dict(unicode=[0x15b], baseGlyphs=['s'], accents=['acutecmb@top']),
	'scaron': dict(unicode=[0x161], baseGlyphs=['s'], accents=['caroncmb@top']),
	'scedilla': dict(unicode=[0x15f], baseGlyphs=['s'], accents=['cedillacmb@bottom']),
	'scircumflex': dict(unicode=[0x15d], baseGlyphs=['s'], accents=['circumflexcmb@top']),
	'scommaaccent': dict(unicode=[0x219], baseGlyphs=['s'], accents=['commaaccentbelowcmb@bottom']),
	'sdotbelow': dict(unicode=[0x1e63], baseGlyphs=['s'], accents=['dotbelowcmb@bottom']),
	'germandbls': dict(unicode=[0xdf]),
	'esh': dict(unicode=[0x283], anchors=['top', 'bottom']),

	'tbar': dict(unicode=[0x167], baseGlyphs=['t'], accents=['overlaystrokeshortcmb@middle'], anchors=['top', 'bottom']),
	'tcaron': dict(unicode=[0x165], baseGlyphs=['t'], accents=['caroncmb.slovak@topRight']),
	'tcedilla': dict(unicode=[0x163], baseGlyphs=['t'], accents=['cedillacmb@bottom']),
	'tcircumflexbelow': dict(unicode=[0x1e71], baseGlyphs=['t'], accents=['circumflexbelowcmb@bottom']),
	'tcommaaccent': dict(unicode=[0x21b], baseGlyphs=['t'], accents=['commaaccentbelowcmb@bottom']),
	'tdotbelow': dict(unicode=[0x1e6d], baseGlyphs=['t'], accents=['dotbelowcmb@bottom']),
	'tlinebelow': dict(unicode=[0x1e6f], baseGlyphs=['t'], accents=['macronbelowcmb@bottom']),
	'tstroke': dict(unicode=[0x2c66], baseGlyphs=['t'], accents=['soliduslongoverlaycmb@middle'], anchors=['top', 'bottom']),
	'thook': dict(unicode=[0x1ad], baseGlyphs=['t'], anchors=['bottom', 'top']),
	'tretroflex': dict(unicode=[0x0288], baseGlyphs=['t'], anchors=['top']),
	'theta.LATN': dict(unicode=[0x03B8], anchors=['top', 'bottom']),

	'uacute': dict(unicode=[0xfa], baseGlyphs=['u'], accents=['acutecmb@top']),
	'ubar': dict(unicode=[0x289], baseGlyphs=['u'], anchors=['top', 'bottom']),
	'ubreve': dict(unicode=[0x16d], baseGlyphs=['u'], accents=['brevecmb@top']),
	'ucaron': dict(unicode=[0x1d4], baseGlyphs=['u'], accents=['caroncmb@top']),
	'ucircumflex': dict(unicode=[0xfb], baseGlyphs=['u'], accents=['circumflexcmb@top']),
	'udieresis': dict(unicode=[0xfc], baseGlyphs=['u'], accents=['dieresiscmb@top']),
	'udieresisacute': dict(unicode=[0x1d8], baseGlyphs=['u'], accents=['dieresisacutecmb@top']),
	'udieresiscaron': dict(unicode=[0x1da], baseGlyphs=['u'], accents=['dieresiscaroncmb@top']),
	'udieresisgrave': dict(unicode=[0x1dc], baseGlyphs=['u'], accents=['dieresisgravecmb@top']),
	'udieresismacron': dict(unicode=[0x1d6], baseGlyphs=['u'], accents=['dieresismacroncmb@top']),
	'udotbelow': dict(unicode=[0x1ee5], baseGlyphs=['u'], accents=['dotbelowcmb@bottom']),
	'ugrave': dict(unicode=[0xf9], baseGlyphs=['u'], accents=['gravecmb@top']),
	'uhookabove': dict(unicode=[0x1ee7], baseGlyphs=['u'], accents=['hookabovecmb@top']),
	'uhorn': dict(unicode=[0x1b0], baseGlyphs=['u'], accents=['horncmb@horn'], anchors=['top', 'bottom']),
	'uhornacute': dict(unicode=[0x1ee9], baseGlyphs=['uhorn'], accents=['acutecmb@top']),
	'uhorndotbelow': dict(unicode=[0x1ef1], baseGlyphs=['uhorn'], accents=['dotbelowcmb@bottom']),
	'uhorngrave': dict(unicode=[0x1eeb], baseGlyphs=['uhorn'], accents=['gravecmb@top']),
	'uhornhookabove': dict(unicode=[0x1eed], baseGlyphs=['uhorn'], accents=['hookabovecmb@top']),
	'uhorntilde': dict(unicode=[0x1eef], baseGlyphs=['uhorn'], accents=['tildecmb@top']),
	'uhungarumlaut': dict(unicode=[0x171], baseGlyphs=['u'], accents=['hungarumlautcmb@top']),
	'umacron': dict(unicode=[0x16b], baseGlyphs=['u'], accents=['macroncmb@top']),
	'uogonek': dict(unicode=[0x173], baseGlyphs=['u'], accents=['ogonekcmb@ogonek']),
	'uogonek.NAV': dict(baseGlyphs=['u'], accents=['ogonekcmb.NAV@bottom']),
	'uring': dict(unicode=[0x16f], baseGlyphs=['u'], accents=['ringabovecmb@top']),
	'utilde': dict(unicode=[0x169], baseGlyphs=['u'], accents=['tildecmb@top']),
	'utildeacute': dict(unicode=[0x1e79], baseGlyphs=['u'], accents=['tildeacutecmb@top']),
	'utildebelow': dict(unicode=[0x1e75], baseGlyphs=['u'], accents=['tildebelowcmb@bottom']),
	'ustroke': dict(unicode=[0xa7b9], baseGlyphs=['u'], accents=['soliduslongoverlaycmb@middle'], anchors=['top', 'bottom']),

	'vhook': dict(unicode=[0x28b], anchors=['top', 'bottom']),
	'upsilon.IPA': dict(unicode=[0x28a], anchors=['top', 'bottom']),
	'vturned': dict(unicode=[0x28c], anchors=['top', 'bottom', 'topRight']),
	'vtilde': dict(unicode=[0x1e7d], baseGlyphs=['v'], accents=['tildecmb@top']),

	'wacute': dict(unicode=[0x1e83], baseGlyphs=['w'], accents=['acutecmb@top']),
	'wcircumflex': dict(unicode=[0x175], baseGlyphs=['w'], accents=['circumflexcmb@top']),
	'wdieresis': dict(unicode=[0x1e85], baseGlyphs=['w'], accents=['dieresiscmb@top']),
	'wgrave': dict(unicode=[0x1e81], baseGlyphs=['w'], accents=['gravecmb@top']),
	'whook': dict(unicode=[0x2c73], baseGlyphs=['w'], anchors=['top', 'bottom']),

	'xdieresis': dict(unicode=[0x1e8d], baseGlyphs=['x'], accents=['dieresiscmb@top']),
	'xdot': dict(unicode=[0x1e8b], baseGlyphs=['x'], accents=['dotaccentcmb@top']),
	'chi.LATN': dict(unicode=[0xAB53], anchors=['top', 'bottom']),

	'yacute': dict(unicode=[0xfd], baseGlyphs=['y'], accents=['acutecmb@top']),
	'ycircumflex': dict(unicode=[0x177], baseGlyphs=['y'], accents=['circumflexcmb@top']),
	'ydieresis': dict(unicode=[0xff], baseGlyphs=['y'], accents=['dieresiscmb@top']),
	'ydotbelow': dict(unicode=[0x1ef5], baseGlyphs=['y'], accents=['dotbelowcmb@bottom']),
	'ygrave': dict(unicode=[0x1ef3], baseGlyphs=['y'], accents=['gravecmb@top']),
	'yhookabove': dict(unicode=[0x1ef7], baseGlyphs=['y'], accents=['hookabovecmb@top']),
	'ymacron': dict(unicode=[0x233], baseGlyphs=['y'], accents=['macroncmb@top']),
	'ytilde': dict(unicode=[0x1ef9], baseGlyphs=['y'], accents=['tildecmb@top']),
	'yhook': dict(unicode=[0x1b4], baseGlyphs=['y'], anchors=['top', 'bottom']),

	'zacute': dict(unicode=[0x17a], baseGlyphs=['z'], accents=['acutecmb@top']),
	'zcaron': dict(unicode=[0x17e], baseGlyphs=['z'], accents=['caroncmb@top']),
	'zdotaccent': dict(unicode=[0x17c], baseGlyphs=['z'], accents=['dotaccentcmb@top']),
	'zcircumflex': dict(unicode=[0x1e91], baseGlyphs=['z'], accents=['circumflexcmb@top']),
	'zdotbelow': dict(unicode=[0x1e93], baseGlyphs=['z'], accents=['dotbelowcmb@bottom']),
	'zstroke': dict(unicode=[0x1b6], baseGlyphs=['z'], accents=['overlaystrokeshortcmb@middle'], anchors=['top', 'bottom']),
	'ezh': dict(unicode=[0x292], anchors=['top', 'bottom']),
	'ezhcaron': dict(unicode=[0x1ef], baseGlyphs=['ezh'], accents=['caroncmb@top']),
	'gamma.IPA': dict(unicode=[0x263], anchors=['top', 'bottom']),

	'saltillo': dict(unicode=[0xA78C]),
	'glottalstop': dict(unicode=[0x0242]),
	'glottalstop.IPA': dict(unicode=[0x0294]),
	'pharyngealvoicedfricative': dict(unicode=[0x0295]),
	'lambdastroke': dict(unicode=[0x019B]),
	'clickretroflex': dict(unicode=[0x01c3], baseGlyphs=['exclam']),
	'clickdental': dict(unicode=[0x01C0]),
	'clicklateral': dict(unicode=[0x01C1], baseGlyphs=['clickdental', 'clickdental']),
	'clickalveolar': dict(unicode=[0x01C2]),
	
	'a.sup': dict(unicode=[0x00AA, 0x1D43]),
	'b.sup': dict(unicode=[0x1D47]),
	'c.sup': dict(unicode=[0x1D9C]),
	'd.sup': dict(unicode=[0x1D48]),
	'e.sup': dict(unicode=[0x1D49]),
	'f.sup': dict(unicode=[0x1DA0]),
	'g.sup': dict(unicode=[0x1D4D]),
	'h.sup': dict(unicode=[0x02B0]),
	'i.sup': dict(unicode=[0x2071]),
	'j.sup': dict(unicode=[0x02B2]),
	'k.sup': dict(unicode=[0xAD4F]),
	'l.sup': dict(unicode=[0x02E1]),
	'm.sup': dict(unicode=[0x1D50]),
	'n.sup': dict(unicode=[0x207F]),
	'o.sup': dict(unicode=[0x00BA, 0x1D52]),
	'p.sup': dict(unicode=[0x1D56]),
	'q.sup': dict(),	
	'r.sup': dict(unicode=[0x02B3]),
	's.sup': dict(unicode=[0x02E2]),
	't.sup': dict(unicode=[0x1D57]),
	'u.sup': dict(unicode=[0x1D58]),
	'v.sup': dict(unicode=[0x1D5B]),
	'w.sup': dict(unicode=[0x02B7]),
	'x.sup': dict(unicode=[0x02E3]),
	'y.sup': dict(unicode=[0x02B8]),
	'z.sup': dict(unicode=[0x1DBB]),
	'eth.sup': dict(unicode=[0x1D9E]),
	'eopen.sup': dict(unicode=[0x1D4B]),
	'schwa.sup': dict(unicode=[0x1D4A], baseGlyphs=['e.sup']),
	'eng.sup': dict(unicode=[0x1D51]),
	'hhook.sup': dict(unicode=[0x02B1], baseGlyphs=['h.sup']),
	'istroke.sup': dict(unicode=[0x1DA4], baseGlyphs=['o.sup']),
	'Ismall.IPA.sup': dict(unicode=[0x1DA6]),
	'nhookleft.sup': dict(unicode=[0x1DAE], baseGlyphs=['n.sup']),
	'oopen.sup': dict(unicode=[0x1D53], baseGlyphs=['c.sup']),
	'obarred.sup': dict(unicode=[0x1DB1], baseGlyphs=['o.sup']),
	'esh.sup': dict(unicode=[0x1DB4]),
	'theta.sup': dict(unicode=[0x1dbf]),
	'ubar.sup': dict(unicode=[0x1DB6], baseGlyphs=['u.sup']),
	'upsilon.IPA.sup': dict(unicode=[0x1DB7]),
	'vhook.sup': dict(unicode=[0x1DB9]),
	'vturned.sup': dict(unicode=[0x1DBA], baseGlyphs=['v.sup']),
	'ezh.sup': dict(unicode=[0x1DBE]),
	'glottalstop.IPA.sup': dict(unicode=[0x02C0]), #old glottalstopmod
	'pharyngealvoicedfricative.sup': dict(unicode=[0x02C1]), #or reversedglottalstop.sup
	

	'circledotted': dict(unicode=[0x25CC], anchors=['top', 'bottom', 'ogonek', 'topRight', 'middle' ]),
	
	# Accents cmb + composite
	'acutecmb': dict(unicode=[0x0301], anchors=['_top', 'top'], isAccent=True),
	'gravecmb': dict(unicode=[0x0300], anchors=['_top', 'top'], isAccent=True),
	'brevecmb': dict(unicode=[0x306], anchors=['_top', 'top'], isAccent=True),
	'invertedbrevecmb': dict(unicode=[0x311],  anchors=['top', '_top'], isAccent=True),
	'inverteddoublebrevecmb': dict(unicode=[0x361], anchors=['_top', 'top'], isAccent=True),
	'circumflexcmb': dict(unicode=[0x0302], anchors=['_top', 'top'], isAccent=True),
	'caroncmb': dict(unicode=[0x30c], anchors=['_top', 'top'], isAccent=True),
	'caroncmb.slovak': dict(anchors=['_topRight'], isAccent=True),
	'dotaccentcmb': dict(unicode=[0x307], anchors=['_top', 'top', '_middle'], isAccent=True),
	'dieresiscmb': dict(unicode=[0x308], anchors=['_top', 'top'], isAccent=True),
	'tildecmb': dict(unicode=[0x0303], anchors=['_top', 'top', '_middle'], isAccent=True),
	'macroncmb': dict(unicode=[0x304], anchors=['_top', 'top'], isAccent=True),
	'hookabovecmb': dict(unicode=[0x0309], anchors=['_top', 'top'], isAccent=True),
	'hungarumlautcmb': dict(unicode=[0x30b], anchors=['top', '_top'], isAccent=True),
	'doublegravecmb': dict(unicode=[0x030F], anchors=['_top', 'top'], isAccent=True),
	'ringabovecmb': dict(unicode=[0x30A], anchors=['_top', 'top'], isAccent=True), 
	'verticallineabovecmb': dict(unicode=[0x030D], anchors=['_top', 'top'], isAccent=True),
	'macrongravecmb': dict(unicode=[0x1dc6], anchors=['_top', 'top'], isAccent=True),
	'acutemacroncmb': dict(unicode=[0x1dc7], anchors=['_top', 'top'], isAccent=True),
	'gravemacroncmb': dict(unicode=[0x1DC5], anchors=['_top', 'top'], isAccent=True),
	'macronacutecmb': dict(unicode=[0x1DC4], anchors=['_top', 'top'], isAccent=True),
	'revcommaaccentcmb': dict(unicode=[0x0312], anchors=['_top', 'top'], isAccent=True),
	'turnedabovecmb': dict(unicode=[0x313], anchors=['_top', 'top'], isAccent=True),
	'turnedcommaabovecmb': dict(unicode=[0x315], anchors=['_topRight'], isAccent=True),
	'dotrightabovecmb': dict(unicode=[0x0358], anchors=['_topRight'], isAccent=True),
	'horncmb': dict(unicode=[0x031B], anchors=['_horn'], isAccent=True),
	'soliduslongoverlaycmb': dict(unicode=[0x338], anchors=['_middle'], isAccent=True),
	'overlaystrokeshortcmb': dict(unicode=[0x0335], anchors=['_middle'], isAccent=True),
	
	#Below cmb
	'dotbelowcmb': dict(unicode=[0x323], anchors=['_bottom', 'bottom'], isAccent=True),
	'cedillacmb': dict(unicode=[0x0327], anchors=['_bottom', 'bottom'], isAccent=True),
	'ogonekcmb': dict(unicode=[0x328], anchors=['_ogonek', 'bottom'], isAccent=True),
	'ogonekcmb.NAV': dict(anchors=['_bottom', 'bottom'], isAccent=True),
	'macronbelowcmb': dict(unicode=[0x331], anchors=['_bottom', 'bottom'], isAccent=True),
	'macrondoublebelowcmb': dict(unicode=[0x035F], anchors=['_bottom', 'bottom'], isAccent=True),
	'minusbelowcmb': dict(unicode=[0x320], anchors=['_bottom', 'bottom'], isAccent=True),
	'lowlinecmb': dict(unicode=[0x332], anchors=['_bottom', 'bottom'], isAccent=True),
	'tildebelowcmb': dict(anchors=['_bottom', 'bottom'], isAccent=True),
	'circumflexbelowcmb': dict(unicode=[0x032D], anchors=['_bottom', 'bottom'], isAccent=True),
	'dieresisbelowcmb': dict(unicode=[0x0324], anchors=['_bottom', 'bottom'], isAccent=True),
	'ringbelowcmb': dict(unicode=[0x0325], anchors=['_bottom', 'bottom'], isAccent=True),
	'invertedbelowbrevecmb': dict(unicode=[0x32f], anchors=['_bottom', 'bottom'], isAccent=True),
	'righthalfringbelowcmb': dict(unicode=[0x0339], anchors=['_bottom', 'bottom'], isAccent=True),
	'commaaccentbelowcmb': dict(unicode=[0x326], anchors=['bottom', '_bottom'], isAccent=True),
	#Double
	'breveacutecmb': dict(anchors=['_top'], isAccent=True, baseGlyphs=['brevecmb'], accents=['acutecmb@top']),
	'brevegravecmb': dict(anchors=['_top'], isAccent=True, baseGlyphs=['brevecmb'], accents=['gravecmb@top']),
	'brevehookcmb': dict(anchors=['_top'], isAccent=True, baseGlyphs=['brevecmb'], accents=['hookabovecmb@top']),
	'brevetildecmb': dict(anchors=['_top'], isAccent=True, baseGlyphs=['brevecmb'], accents=['tildecmb@top']),
	'circumflexacutecmb': dict(anchors=['_top'], isAccent=True, baseGlyphs=['circumflexcmb'], accents=['acutecmb@top']),
	'circumflexgravecmb': dict(anchors=['_top'], isAccent=True, baseGlyphs=['circumflexcmb'], accents=['gravecmb@top']),
	'circumflexhookcmb': dict(anchors=['_top'], isAccent=True, baseGlyphs=['circumflexcmb'], accents=['hookabovecmb@top']),
	'circumflextildecmb': dict(anchors=['_top'], isAccent=True, baseGlyphs=['circumflexcmb'], accents=['tildecmb@top']),
	'dieresisacutecmb': dict(anchors=['_top'], isAccent=True, baseGlyphs=['dieresiscmb'], accents=['acutecmb@top']),
	'dieresisgravecmb': dict(anchors=['_top'], isAccent=True, baseGlyphs=['dieresiscmb'], accents=['acutecmb@top']), 
	'dieresiscaroncmb': dict(anchors=['_top'], isAccent=True, baseGlyphs=['dieresiscmb'], accents=['caroncmb@top']),
	'dieresismacroncmb': dict(anchors=['_top'], isAccent=True, baseGlyphs=['dieresiscmb'], accents=['macroncmb@top']),
	'ringacutecmb': dict(anchors=['_top'], isAccent=True, baseGlyphs=['ringabovecmb'], accents=['acutecmb@top']),
	'tildeacutecmb': dict(anchors=['_top'], isAccent=True, baseGlyphs=['tildecmb'], accents=['acutecmb@top']),
	
	#.Cap
	'acute.cap': dict(anchors=['_top', 'top'], isAccent=True),
	'breve.cap': dict(anchors=['_top', 'top'], isAccent=True),
	'caron.cap': dict(anchors=['_top', 'top'], isAccent=True),
	'circumflex.cap': dict(anchors=['_top', 'top'], isAccent=True),
	'dieresis.cap': dict(anchors=['_top', 'top'], isAccent=True),
	'dotaccent.cap': dict(anchors=['_top', 'top'], isAccent=True),
	'doublegrave.cap': dict(anchors=['_top', 'top'], isAccent=True),
	'grave.cap': dict(anchors=['_top', 'top'], isAccent=True),
	'hookabove.cap': dict(anchors=['_top', 'top'], isAccent=True),
	'hungarumlaut.cap': dict(anchors=['_top', 'top'], isAccent=True),
	'invertedbreve.cap': dict(anchors=['_top', 'top'], isAccent=True),
	'macron.cap': dict(baseGlyphs=['macron'], anchors=['_top', 'top'], isAccent=True),
	'ring.cap': dict(anchors=['_top', 'top'], isAccent=True),
	'tilde.cap': dict(anchors=['_top', 'top'], isAccent=True),
	'breveacute.cap': dict(anchors=['_top'], isAccent=True),
	'brevegrave.cap': dict(anchors=['_top'], isAccent=True),
	'brevehook.cap': dict(anchors=['_top'], isAccent=True),
	'brevetilde.cap': dict(anchors=['_top'], isAccent=True),
	'circumflexacute.cap': dict(anchors=['_top'], isAccent=True),
	'circumflexgrave.cap': dict(anchors=['_top'], isAccent=True),
	'circumflexhook.cap': dict(anchors=['_top'], isAccent=True),
	'circumflextilde.cap': dict(anchors=['_top'], isAccent=True),
	'dieresisacute.cap': dict(anchors=['_top'], isAccent=True),
	'dieresiscaron.cap': dict(anchors=['_top'], isAccent=True),
	'dieresisgrave.cap': dict(anchors=['_top'], isAccent=True),
	'dieresismacron.cap': dict(anchors=['_top'], isAccent=True),
	'ringacute.cap': dict(anchors=['_top'], isAccent=True),
	'tildeacute.cap': dict(anchors=['_top'], isAccent=True),
	'soliduslongoverlaycmb.cap': dict(anchors=['_middle'], isAccent=True),
	# Spacing modifiers
	'acute': dict(unicode=[0xb4], baseGlyphs=['acutecmb'], isAccent=True),
	'breve': dict(unicode=[0x2d8], baseGlyphs=['brevecmb'], isAccent=True),
	'caron': dict(unicode=[0x2c7], baseGlyphs=['caroncmb'], isAccent=True),
	'cedilla': dict(unicode=[0xb8], baseGlyphs=['cedillacmb'], isAccent=True),
	'circumflex': dict(unicode=[0x2c6], baseGlyphs=['circumflexcmb'], isAccent=True),
	'commaaccent': dict(unicode=[0xF6C3], baseGlyphs=['commaaccentbelowcmb'], isAccent=True),
	'dieresis': dict(unicode=[0xa8], baseGlyphs=['dieresiscmb'], isAccent=True),
	'dotaccent': dict(unicode=[0x2d9], baseGlyphs=['dotaccentcmb'], isAccent=True),
	'grave': dict(unicode=[0x60], baseGlyphs=['gravecmb'], isAccent=True),
	'hungarumlaut': dict(unicode=[0x2dd], baseGlyphs=['hungarumlautcmb'], isAccent=True),
	'macron': dict(unicode=[0xaf, 0x02C9], baseGlyphs=['macroncmb'], isAccent=True),
	'ogonek': dict(unicode=[0x2db], baseGlyphs=['ogonekcmb'], isAccent=True),
	'ring': dict(unicode=[0x2da], baseGlyphs=['ringabovecmb'], isAccent=True),
	'tilde': dict(unicode=[0x2dc], baseGlyphs=['tildecmb'], isAccent=True),
	'dieresisacute': dict(unicode=[0x1fee], baseGlyphs=['dieresisacutecmb'], isAccent=True),
	'dieresisgrave': dict(unicode=[0x1fed], baseGlyphs=['dieresisgravecmb'], isAccent=True),
	'undertie': dict(unicode=[0x203f], isAccent=True),
	'commaturnedmod': dict(unicode=[0x2bb], baseGlyphs=['quoteright'], isAccent=True),
	'apostrophemod': dict(unicode=[0x2bc], baseGlyphs=['quoteright'], isAccent=True),
	'apostrophedblmod': dict(unicode=[0x02EE], baseGlyphs=['quotedblright'], isAccent=True),
	'ringhalfleftmod': dict(unicode=[0x2bf], isAccent=True),  #removed anchors
	'primemod': dict(unicode=[0x02B9], baseGlyphs=['quotesingle'], isAccent=True),
	'minussignmod': dict(unicode=[0x02D7], isAccent=True),
	'shortequalsmod': dict(unicode=[0xA78A], isAccent=True),
	'colonmod': dict(unicode=[0xA789], baseGlyphs=['colon'], isAccent=True),
	'ellipsismidhorizontal': dict(unicode=[0x22ef], isAccent=True),

}