specialChars = {
    'Alpha.LATN': [
    	dict(glyphName='C'),
    	dict(glyphName='I')],
    'Acircle': [
    	dict(glyphName='A'),
    	dict(glyphName='at')],
    'AE': [
    	dict(glyphName='A'),
    	dict(glyphName='E')],
    'Bhook': [dict(glyphName='B')],
    'Chook': [dict(glyphName='C'), dict(glyphName='dotlessj', fallback=['j'], rotate=180)],
    'Dhook': [dict(glyphName='D')],
    'Dstroke': [
    	dict(glyphName='D'),
    	dict(glyphName='emdash.cap', fallback=['emdash'])],
    'Ereversed': [dict(glyphName='E', scale=(-1,1))],
    'Schwa': [
    	dict(glyphName='O'),
    	dict(glyphName='e', scale='capHeight', rotate=180)],
    'Eopen': [
    	dict(glyphName='three', scale=(-1, 1)),
    	dict(glyphName='E')],
    'Fhook': [
    	dict(glyphName='F'),
    	dict(glyphName='dotlessj', fallback=['j'])],
    'Ghook': [dict(glyphName='G'), dict(glyphName='dotlessj', fallback=['j'], rotate=180)],
    'Scriptg': 
    	[dict(glyphName='C'),
    	dict(glyphName='g')],
    'Hbar': [
    	dict(glyphName='H'),
    	dict(glyphName='emdash.cap', fallback=['emdash'])],
    'Hhook': [dict(glyphName='H')],
    'Hturned': [dict(glyphName='H')],
    'Ismall': [dict(glyphName='T'), dict(glyphName='T', rotate=180)],
    'Iota.LATN': [dict(glyphName='I')],
    'Jcrossedtail': [dict(glyphName='J')],
    'Khook': [dict(glyphName='K')],
    'Lslash': [dict(glyphName='L', decompose=False), dict(glyphName='hyphen.cap', fallback=['hyphen'])],
    'Lbelt': [dict(glyphName='L', decompose=False)],
    'Nhookleft': [dict(glyphName='N'), dict(glyphName='dotlessj', fallback=['j'])],
    'Eng': [dict(glyphName='N'), dict(glyphName='dotlessj', fallback=['j'])],
    'Eng.locl': [dict(glyphName='eng.locl', fallback=['n'])],
    'Obar': [dict(glyphName='O', decompose=False), dict(glyphName='emdash.cap', fallback=['emdash'])],
    'Oopen': [dict(glyphName='C', rotate=180)],
    'OE': [dict(glyphName='O'), dict(glyphName='E')],
    'Phook': [dict(glyphName='P')],
    'Thorn': [dict(glyphName='I'), dict(glyphName='P')],
    'Rtail': [dict(glyphName='R'), dict(glyphName='dotlessj', fallback=['j'], scale=(-1, 1))],
    'yr': [dict(glyphName='R')],
    'Germandbls': [dict(glyphName='F'), dict(glyphName='S')],
    'Esh': [dict(glyphName='summation', fallback=['E'])],
    'Thook': [dict(glyphName='T')],
    'Tretroflexhook': [dict(glyphName='T'), dict(glyphName='dotlessj', scale=(-1, 1))],
    'Theta.LATN': [dict(glyphName='zero.LP', fallback=['O']), dict(glyphName='emdash.cap', fallback=['emdash'])],
    'Ubar': [dict(glyphName='U', decompose=False), dict(glyphName='emdash.cap', fallback=['emdash'])],
    'Vhook': [dict(glyphName='U')],
    'Vturned': [dict(glyphName='V', decompose=False, rotate=180)],
    'Upsilon.LATN': [dict(glyphName='Omega', fallback=['Ohm, O'], decompose=False, rotate=180)],
    'Whook': [dict(glyphName='W')],
    'Chi.LATN': [dict(glyphName='X')],
    'Yturnedsans': [dict(glyphName='Y', decompose=False, rotate=180)],
    'Yhook': [dict(glyphName='Y')],
    'Ezh': [dict(glyphName='Z'), dict(glyphName='three')],
    'Gamma.LATN': [dict(glyphName='V')],
    'Glottalstop': [dict(glyphName='question'), dict(glyphName='I')],
    'Saltillo': [dict(glyphName='quotesingle')],

    'alpha.IPA': [dict(glyphName='alpha', fallback=['u'])],
    'ae': [dict(glyphName='a'), dict(glyphName='e')],
    'bhook': [dict(glyphName='b')],
    'chook': [dict(glyphName='c')],
    'dhook': [dict(glyphName='d')],
    'dtail': [dict(glyphName='d'), dict(glyphName='dotlessj')],
    'dstroke': [dict(glyphName='d', decompose=False), dict(glyphName='hyphen')],
    'eth': [dict(glyphName='d'), dict(glyphName='o')],
    'estroke': [dict(glyphName='e', decompose=False), dict(glyphName='slash')],
    'eturned': [dict(glyphName='e', rotate=180)],
    'schwa': [dict(glyphName='e', rotate=180)],
    'eopen': [dict(glyphName='three'), dict(glyphName='c')],
    'fhook': [dict(glyphName='f'), dict(glyphName='dotlessj')],
    'gstroke': [dict(glyphName='g', decompose=False), dict(glyphName='endash', fallback='emdash')],
    'gscript.IPA': [dict(glyphName='g'), dict(glyphName='c'), dict(glyphName='dotlessj')],
    'ghook': [dict(glyphName='g'), dict(glyphName='c'), dict(glyphName='dotlessj')],
    'hhook': [dict(glyphName='h')],
    'hturned': [dict(glyphName='h')],
    'dotlessi': [dict(glyphName='i')],
    'Ismall.IPA': [dict(glyphName='dotlessi')],
    'iota.IPA': [dict(glyphName='iota', fallback=['u'])],
    'dotlessj': [dict(glyphName='j')],
    'jcrossedtail': [dict(glyphName='j')],
    'ij': [dict(glyphName='i', decompose=False), dict(glyphName='j', decompose=False, addWidth=True)],
    'kra': [dict(glyphName='k')],
    'khook': [dict(glyphName='k')],
    'lslash': [dict(glyphName='l', decompose=False), dict(glyphName='slash')],
    'ldot': [dict(glyphName='l', decompose=False)],
    'lbelt': [dict(glyphName='l', decompose=False)],
    'nhookleft': [dict(glyphName='n'), dict(glyphName='dotlessj')],
    'eng': [dict(glyphName='n'), dict(glyphName='dotlessj')],
    'oslash': [dict(glyphName='o', decompose=False), dict(glyphName='slash')],
    'oopen': [dict(glyphName='c', rotate=180)],
    'obarred': [dict(glyphName='o'), dict(glyphName='endash', fallback='emdash')],
    'oe': [dict(glyphName='o'), dict(glyphName='e')],
    'phook': [dict(glyphName='p')],
    'pstroke': [dict(glyphName='p'), dict(glyphName='endash', fallback='emdash')],
    'thorn': [dict(glyphName='l'), dict(glyphName='p')],
    'rtail.IPA': [dict(glyphName='r'), dict(glyphName='dotlessj')],
    'Rsmall': [dict(glyphName='R', scale='xHeight')],
    'germandbls': [dict(glyphName='f'), dict(glyphName='s')],
    'esh': [dict(glyphName='f'), dict(glyphName='dotlessj')],
    'thook': [dict(glyphName='t')],
    'tretroflex': [dict(glyphName='t'), dict(glyphName='dotlessj', scale=(-1, 1))],
    'ubar': [dict(glyphName='u', decompose=False), dict(glyphName='endash', fallback='emdash')],
    'theta.LATN': [dict(glyphName='Theta.LATN', fallback=['zero','O']), dict(glyphName='overlaystrokeshortcmb', fallback=['hyphen'])],
    'vhook': [dict(glyphName='u')],
    'upsilon.IPA': [dict(glyphName='Omega', fallback=['o'])],
    'vturned': [dict(glyphName='v', decompose=False, rotate=180)],
    'whook': [dict(glyphName='w')],
    'chi.LATN': [dict(glyphName='x')],
    'yhook': [dict(glyphName='y')],
    'ezh': [dict(glyphName='three'), dict(glyphName='z')],
    'gamma.IPA': [dict(glyphName='v')],
    'saltillo': [dict(glyphName='quotesingle')],
    'glottalstop': [dict(glyphName='question')],
    'glottalstop.IPA': [dict(glyphName='l'), dict(glyphName='question')],
    'pharyngealvoicedfricative': [dict(glyphName='l'), dict(glyphName='question', scale=(-1, 1))],
    'lambdastroke': [dict(glyphName='lambda', fallback=['j']), dict(glyphName='hyphen')],
    'clickdental': [dict(glyphName='bar')],
    'clickalveolar': [dict(glyphName='clickdental', decompose=False), dict(glyphName='equal', decompose=False)],
    
    'a.sup': [dict(glyphName='a', scale='scaleRatio', translate=(0, 'ordinalHeight'))], 
    'b.sup': [dict(glyphName='b', scale='scaleRatio', translate=(0, 'ordinalHeight'))],
    'c.sup': [dict(glyphName='c', scale='scaleRatio', translate=(0, 'ordinalHeight'))],
    'd.sup': [dict(glyphName='d', scale='scaleRatio', translate=(0, 'ordinalHeight'))],
    'e.sup': [dict(glyphName='e', scale='scaleRatio', translate=(0, 'ordinalHeight'))],
    'f.sup': [dict(glyphName='f', scale='scaleRatio', translate=(0, 'ordinalHeight'))],
    'g.sup': [dict(glyphName='g', scale='scaleRatio', translate=(0, 'ordinalHeight'))],
    'h.sup': [dict(glyphName='h', scale='scaleRatio', translate=(0, 'ordinalHeight'))], #OL
    'i.sup': [dict(glyphName='i', scale='scaleRatio', translate=(0, 'ordinalHeight'))],
    'j.sup': [dict(glyphName='j', scale='scaleRatio', translate=(0, 'ordinalHeight'))],
    'k.sup': [dict(glyphName='k', scale='scaleRatio', translate=(0, 'ordinalHeight'))],
    'l.sup': [dict(glyphName='l', scale='scaleRatio', translate=(0, 'ordinalHeight'))],
    'm.sup': [dict(glyphName='m', scale='scaleRatio', translate=(0, 'ordinalHeight'))],
    'n.sup': [dict(glyphName='n', scale='scaleRatio', translate=(0, 'ordinalHeight'))], #OL
    'o.sup': [dict(glyphName='o', scale='scaleRatio', translate=(0, 'ordinalHeight'))], 
    'p.sup': [dict(glyphName='p', scale='scaleRatio', translate=(0, 'ordinalHeight'))],	
    'q.sup': [dict(glyphName='q', scale='scaleRatio', translate=(0, 'ordinalHeight'))],
    'r.sup': [dict(glyphName='r', scale='scaleRatio', translate=(0, 'ordinalHeight'))],
    's.sup': [dict(glyphName='s', scale='scaleRatio', translate=(0, 'ordinalHeight'))],
    't.sup': [dict(glyphName='t', scale='scaleRatio', translate=(0, 'ordinalHeight'))],
    'u.sup': [dict(glyphName='u', scale='scaleRatio', translate=(0, 'ordinalHeight'))],
    'v.sup': [dict(glyphName='v', scale='scaleRatio', translate=(0, 'ordinalHeight'))],
    'w.sup': [dict(glyphName='w', scale='scaleRatio', translate=(0, 'ordinalHeight'))], #OL
    'x.sup': [dict(glyphName='x', scale='scaleRatio', translate=(0, 'ordinalHeight'))],
    'y.sup': [dict(glyphName='y', scale='scaleRatio', translate=(0, 'ordinalHeight'))], #OL
    'z.sup': [dict(glyphName='z', scale='scaleRatio', translate=(0, 'ordinalHeight'))], #OL
    'eth.sup': [dict(glyphName='eth', scale='scaleRatio', translate=(0, 'ordinalHeight'))],
    'eopen.sup': [dict(glyphName='eopen', scale='scaleRatio', translate=(0, 'ordinalHeight'))],
    'schwa.sup': [dict(glyphName='schwa', scale='scaleRatio', translate=(0, 'ordinalHeight'))],
    'eng.sup': [dict(glyphName='eng', scale='scaleRatio', translate=(0, 'ordinalHeight'))],
    'iota.IPA.sup': [dict(glyphName='iota.IPA', scale='scaleRatio', translate=(0, 'ordinalHeight'))],
    'hhook.sup': [dict(glyphName='hhook', scale='scaleRatio', translate=(0, 'ordinalHeight'))],
    'istroke.sup': [dict(glyphName='istroke', scale='scaleRatio', translate=(0, 'ordinalHeight'))],
    'Ismall.IPA.sup': [dict(glyphName='Ismall.IPA', scale='scaleRatio', translate=(0, 'ordinalHeight'))],
    'nhookleft.sup': [dict(glyphName='nhookleft', scale='scaleRatio', translate=(0, 'ordinalHeight'))],
    'oopen.sup': [dict(glyphName='oopen', scale='scaleRatio', translate=(0, 'ordinalHeight'))],
    'obarred.sup': [dict(glyphName='obarred', scale='scaleRatio', translate=(0, 'ordinalHeight'))],
    'esh.sup': [dict(glyphName='esh', scale='scaleRatio', translate=(0, 'ordinalHeight'))],
    'theta.sup': [dict(glyphName='theta.latn', fallback=['theta'], scale='scaleRatio', translate=(0, 'ordinalHeight'))], #OL
    'ubar.sup': [dict(glyphName='ubar', scale='scaleRatio', translate=(0, 'ordinalHeight'))],
    'upsilon.IPA.sup': [dict(glyphName='upsilon.IPA', scale='scaleRatio', translate=(0, 'ordinalHeight'))],
    'vhook.sup': [dict(glyphName='vhook', scale='scaleRatio', translate=(0, 'ordinalHeight'))],
    'vturned.sup': [dict(glyphName='vturned', scale='scaleRatio', translate=(0, 'ordinalHeight'))],
    'ezh.sup': [dict(glyphName='ezh', scale='scaleRatio', translate=(0, 'ordinalHeight'))],
    'glottalstop.IPA.sup': [dict(glyphName='glottalstop.IPA', scale='scaleRatio', translate=(0, 'ordinalHeight'))], #OL
    'pharyngealvoicedfricative.sup': [dict(glyphName='pharyngealvoicedfricative', scale='scaleRatio', translate=(0, 'ordinalHeight'))], 

#Cmb diacritics
    'invertedbrevecmb': [dict(glyphName="brevecmb", decompose=False, rotate=180)],
    'turnedabovecmb': [dict(glyphName="commaaccentbelowcmb", decompose=False, translate=(0, 'capHeight'))],
    'turnedcommaabovecmb': [dict(glyphName="commaaccentbelowcmb", decompose=False, translate=(0, 'capHeight'))],
    'dotrightabovecmb': [dict(glyphName='dotaccentcmb',decompose=False)],
    'ogonekcmb.NAV': [dict(glyphName='ogonekcmb', decompose=False)],
    'ringacutecmb': [dict(glyphName='ringabovecmb', decompose=False), dict(glyphName='acutecmb', decompose=False)],
    'ringhalfleftmod': [dict(glyphName='righthalfringbelowcmb', decompose=False, rotate=180, translate=(0, 'capHeight'))],
    'soliduslongoverlaycmb': [dict(glyphName='slash')],
    'inverteddoublebrevecmb': [dict(glyphName='parenright', rotate=90)],
    'macrongravecmb': [dict(glyphName='macroncmb'), dict(glyphName='gravecmb')],
    'acutemacroncmb': [dict(glyphName='macroncmb'), dict(glyphName='acutecmb')],
    'gravemacroncmb': [dict(glyphName='macrongravecmb', decompose=False, rotate=180)],
    'macronacutecmb': [dict(glyphName='acutemacroncmb', decompose=False, rotate=180)],
    'minusbelowcmb': [dict(glyphName='minus', decompose=False, translate=(0, 'descender'))],
    'macronbelowcmb': [dict(glyphName='macroncmb', decompose=False, translate=(0, 'descender'))],
    'macrondoublebelowcmb': [dict(glyphName='macronbelowcmb'), dict(glyphName='macronbelowcmb', translate=(400,0))],
    'dotbelowcmb': [dict(glyphName='dotaccentcmb', decompose=False, translate=(0, 'descender'))],
    'tildebelowcmb': [dict(glyphName='tildecmb', decompose=False, translate=(0, 'descender'))],
    'circumflexbelowcmb': [dict(glyphName='circumflexcmb', decompose=False, translate=(0, 'descender'))],
    'dieresisbelowcmb': [dict(glyphName='dieresiscmb', decompose=False, translate=(0, 'descender'))],
    'ringbelowcmb': [dict(glyphName='ringabovecmb', decompose=False, translate=(0, 'descender'))],
    'invertedbelowbrevecmb': [dict(glyphName='invertedbrevecmb', decompose=False, translate=(0, 'descender'))],
    'overlaystrokeshortcmb': [dict(glyphName='hyphen', decompose=False)],
#Double
	'ringacutecmb': [dict(glyphName='ringabovecmb', decompose=False),dict(glyphName='acutecmb', decompose=False)],
	'breveacutecmb': [dict(glyphName='brevecmb', decompose=False),dict(glyphName='acutecmb', decompose=False)],
	'brevegravecmb': [dict(glyphName='brevecmb', decompose=False),dict(glyphName='gravecmb', decompose=False)],
	'brevehookcmb': [dict(glyphName='brevecmb', decompose=False),dict(glyphName='hookabovecmb', decompose=False)],
	'brevetildecmb': [dict(glyphName='brevecmb', decompose=False),dict(glyphName='tildecmb', decompose=False)],
	'dieresisacutecmb': [dict(glyphName='dieresiscmb', decompose=False),dict(glyphName='acutecmb', decompose=False)],
	'dieresisgravecmb': [dict(glyphName='dieresiscmb', decompose=False),dict(glyphName='gravecmb', decompose=False)],
	'dieresiscaroncmb': [dict(glyphName='dieresiscmb', decompose=False), dict(glyphName='caroncmb', decompose=False)],
	'dieresismacroncmb': [dict(glyphName='dieresiscmb', decompose=False),dict(glyphName='macroncmb', decompose=False)],
	'circumflexacutecmb': [dict(glyphName='circumflexcmb', decompose=False),dict(glyphName='acutecmb', decompose=False)],
	'circumflexgravecmb': [dict(glyphName='circumflexcmb', decompose=False),dict(glyphName='gravecmb', decompose=False)],
	'circumflexhookcmb': [dict(glyphName='circumflexcmb', decompose=False),dict(glyphName='hookabovecmb', decompose=False)],
	'circumflextildecmb': [dict(glyphName='circumflexcmb', decompose=False),dict(glyphName='tildecmb', decompose=False)],
	'tildeacutecmb': [dict(glyphName='tildecmb', decompose=False),dict(glyphName='acutecmb', decompose=False)],

    'acute.cap': [dict(glyphName="acutecmb", translate=(0, 'capAccents'))],
    'breve.cap': [dict(glyphName="brevecmb", translate=(0, 'capAccents'))],
    'caron.cap': [dict(glyphName="caroncmb", translate=(0, 'capAccents'))],
    'circumflex.cap': [dict(glyphName="circumflexcmb", translate=(0, 'capAccents'))],
    'dieresis.cap': [dict(glyphName="dieresiscmb", decompose=False, translate=(0, 'capAccents'))],
    'dotaccent.cap': [dict(glyphName="dotaccentcmb", decompose=False, translate=(0, 'capAccents'))],
    'doublegrave.cap': [dict(glyphName="doublegravecmb", translate=(0, 'capAccents'))],
    'grave.cap': [dict(glyphName="gravecmb", translate=(0, 'capAccents'))],
    'hookabove.cap': [dict(glyphName="hookabovecmb", translate=(0, 'capAccents'))],
    'hungarumlaut.cap': [dict(glyphName="hungarumlautcmb", translate=(0, 'capAccents'))],
    'invertedbreve.cap': [dict(glyphName="invertedbrevecmb", translate=(0, 'capAccents'))],
    'macron.cap': [dict(glyphName="macroncmb", decompose=False, translate=(0, 'capAccents'))],
    'ring.cap': [dict(glyphName="ringabovecmb", decompose=False, translate=(0, 'capAccents'))],
    'tilde.cap': [dict(glyphName="tildecmb", translate=(0, 'capAccents'))],
    'breveacute.cap': [dict(glyphName="breveacutecmb", translate=(0, 'capAccents'))],
    'brevegrave.cap': [dict(glyphName="brevegravecmb", translate=(0, 'capAccents'))],
    'brevehook.cap': [dict(glyphName="brevehookcmb", translate=(0, 'capAccents'))],
    'brevetilde.cap': [dict(glyphName="brevetildecmb", translate=(0, 'capAccents'))],
    'circumflexacute.cap': [dict(glyphName="circumflexacutecmb", translate=(0, 'capAccents'))],
    'circumflexgrave.cap': [dict(glyphName="circumflexgravecmb", translate=(0, 'capAccents'))],
    'circumflexhook.cap': [dict(glyphName="circumflexhookcmb", translate=(0, 'capAccents'))],
    'circumflextilde.cap': [dict(glyphName="circumflextildecmb", translate=(0, 'capAccents'))],
    'dieresisacute.cap': [dict(glyphName="dieresisacutecmb", translate=(0, 'capAccents'))],
    'dieresiscaron.cap': [dict(glyphName="dieresiscaroncmb", translate=(0, 'capAccents'))],
    'dieresisgrave.cap': [dict(glyphName="dieresisgravecmb", translate=(0, 'capAccents'))],
    'dieresismacron.cap': [dict(glyphName="dieresismacroncmb", translate=(0, 'capAccents'))],
    'ringacute.cap': [dict(glyphName="ringacutecmb", translate=(0, 'capAccents'))],
    'tildeacute.cap': [dict(glyphName="tildeacutecmb", translate=(0, 'capAccents'))],
    'revcommaaccentcmb': [dict(glyphName='commaaccentbelowcmb', rotate=180, decompose=False, translate=(0, 'capHeight'))],
    'soliduslongoverlaycmb.cap': [dict(glyphName='soliduslongoverlaycmb')],
    
    'minussignmod': [dict(glyphName='macronbelowcmb', decompose=False, translate=(0, 'xHeight'))],
    'shortequalsmod': [dict(glyphName='minussignmod', decompose=False, translate=(0, -60)),dict(glyphName='minussignmod', decompose=False, translate=(0, 60))],
    'undertie': [dict(glyphName='inverteddoublebrevecmb', decompose=False, rotate=180, translate=(0, -500))],
    'ringhalfleftmod': [dict(glyphName='righthalfringbelowcmb', decompose=False, rotate=180, translate=(0,'capHeight'))],


    'ellipsismidhorizontal': [dict(glyphName='ellipsis', decompose=False, translate=(0, 'xHeight'))],

}