from AppKit import NSColor

glyphInfoBackgroundColor = NSColor.colorWithCalibratedRed_green_blue_alpha_(.9, .9, .9, 1.0)
glyphInfoBackgroundColorDarkMode = NSColor.colorWithCalibratedRed_green_blue_alpha_(.1, .1, .1, 1.0)
glyphInfoLineColor = NSColor.colorWithCalibratedRed_green_blue_alpha_(.7, .7, .75, 1.0)
glyphInfoLineColorDarkMode = NSColor.colorWithCalibratedRed_green_blue_alpha_(.2, .2, .25, 1.0)
glyphInfoIconColor = NSColor.colorWithCalibratedWhite_alpha_(0, .25)
glyphInfoIconColorDarkMode = NSColor.colorWithCalibratedWhite_alpha_(1, .25)
glyphInfoHeaderColor = NSColor.colorWithCalibratedRed_green_blue_alpha_(.82, .82, .84, 1.0)
glyphInfoHeaderColorDarkMode = NSColor.colorWithCalibratedRed_green_blue_alpha_(.1, .1, .14, 1.0)
glyphInfoSelectionColor = NSColor.colorWithCalibratedRed_green_blue_alpha_(.9, .9, 1, 1.0)
glyphInfoSelectionColorDarkMode = NSColor.colorWithCalibratedRed_green_blue_alpha_(.1, .1, .3, 1)
glyphInfoKernGlyphColor = NSColor.colorWithCalibratedRed_green_blue_alpha_(.77, .77, .79, 1.0)
glyphInfoKernGlyphColorDarkMode = NSColor.colorWithCalibratedRed_green_blue_alpha_(.2, .2, .29, 1.0)
glyphInfoKernGroupColor = NSColor.colorWithCalibratedRed_green_blue_alpha_(.7, .7, .8, 1.0)
glyphInfoKernGroupColorDarkMode = NSColor.colorWithCalibratedRed_green_blue_alpha_(.25, .25, .35, 1.0)
glyphInfoKernExceptionColor = NSColor.colorWithCalibratedRed_green_blue_alpha_(.8, .7, .7, 1.0)
glyphInfoKernExceptionColorDarkMode = NSColor.colorWithCalibratedRed_green_blue_alpha_(.2, .1, .1, 1.0)
glyphInfoKernPositiveColor = NSColor.colorWithCalibratedRed_green_blue_alpha_(.77, 1, .77, 1)
glyphInfoKernPositiveColorDarkMode = NSColor.colorWithCalibratedRed_green_blue_alpha_(0, 0.15, 0, 1)
glyphInfoKernNegativeColor = NSColor.colorWithCalibratedRed_green_blue_alpha_(1, .8, .8, 1)
glyphInfoKernNegativeColorDarkMode = NSColor.colorWithCalibratedRed_green_blue_alpha_(0.15, 0, 0, 1)
glyphInfoKernZeroColor = NSColor.colorWithCalibratedRed_green_blue_alpha_(1, 1, .7, 1)
glyphInfoKernZeroColorDarkMode = NSColor.colorWithCalibratedRed_green_blue_alpha_(.2, .2, 0, 1)

listViewGroupColor = NSColor.colorWithCalibratedRed_green_blue_alpha_(.3, .4, .8, 1)
listViewSelectedGroupColor = NSColor.colorWithCalibratedRed_green_blue_alpha_(.9, .9, 1.0, 1.0)
groupListViewPillColor = NSColor.colorWithCalibratedRed_green_blue_alpha_(.75, .75, .8, 1.0)

editViewGlyphStackColor = NSColor.colorWithCalibratedRed_green_blue_alpha_(0, 0, .2, .25)
editViewGlyphStackColorDarkMode = NSColor.colorWithCalibratedRed_green_blue_alpha_(.4, .4, 0.95, .5)
editViewSelectionGroupColor = NSColor.colorWithCalibratedRed_green_blue_alpha_(.6, .6, .8, 1.0)
editViewSelectionGroupColorDarkMode = NSColor.colorWithCalibratedRed_green_blue_alpha_(0.1, 0.1, .3, 1.0)
editViewSelectionGlyphColor = NSColor.colorWithCalibratedRed_green_blue_alpha_(.75, .75, .77, 1.0)
editViewSelectionGlyphColorDarkMode = NSColor.colorWithCalibratedRed_green_blue_alpha_(.18, .18, .25, 1.0)
editViewSelectionExceptionColor = NSColor.colorWithCalibratedRed_green_blue_alpha_(.8, .6, .6, 1.0)
editViewSelectionExceptionColorDarkMode = NSColor.colorWithCalibratedRed_green_blue_alpha_(.3, .1, .1, 1.0)

editViewMultiplePairDividerLineColor = NSColor.colorWithCalibratedRed_green_blue_alpha_(.7, .7, .75, 1.0)
editViewMultiplePairDividerLineColorDarkMode = NSColor.colorWithCalibratedRed_green_blue_alpha_(.2, .2, .2, 1.0)
editViewMultiplPairDeselectColor = NSColor.colorWithCalibratedWhite_alpha_(.2, 1.0)

groupStackViewMaskColor = NSColor.colorWithCalibratedWhite_alpha_(0, .9)
groupStackViewMaskColorDarkMode = NSColor.colorWithCalibratedWhite_alpha_(1, .9)
groupStackViewGlyphColor = NSColor.colorWithCalibratedWhite_alpha_(0, .4)
groupStackViewGlyphColorDarkMode = NSColor.colorWithCalibratedWhite_alpha_(1, .4)
HUDGroupStackViewMaskColor = NSColor.colorWithCalibratedWhite_alpha_(0, .8)
HUDGroupStackViewMaskColorDarkMode = NSColor.colorWithCalibratedWhite_alpha_(1, .8)
HUDGroupStackViewGlyphColor = NSColor.colorWithCalibratedWhite_alpha_(1, .3)
HUDGroupStackViewGlyphColorDarkMode = NSColor.colorWithCalibratedWhite_alpha_(0, .3)

conflictResolutionListExceptionColor = NSColor.colorWithCalibratedRed_green_blue_alpha_(.8, 0, 0, 1.0)
conflictResolutionListGroupValueColor = listViewGroupColor
conflictResolutionListFollowGroupColor = NSColor.grayColor()
conflictResolutionListGroupValuePillColor = NSColor.colorWithCalibratedRed_green_blue_alpha_(.55, .7, .9, 1.0)
conflictResolutionListFollowGroupPillColor = NSColor.colorWithCalibratedWhite_alpha_(.7, 1.0)
conflictResolutionListExceptionPillColor = NSColor.colorWithCalibratedRed_green_blue_alpha_(1, .3, .3, 1)

topographyEditViewHeaderCornerColor1 = NSColor.colorWithCalibratedWhite_alpha_(.45, 1)
topographyEditViewHeaderCornerColor2 = NSColor.colorWithCalibratedWhite_alpha_(.65, 1)
topographyEditViewHeaderBaseColor = NSColor.colorWithCalibratedWhite_alpha_(.8, 1)
topographyEditViewHeaderHighlightColor = NSColor.colorWithCalibratedWhite_alpha_(.9, 1)
topographyEditViewHeaderSelectionColor = NSColor.colorWithCalibratedRed_green_blue_alpha_(.2, .3, .7, .15)
topographyEditViewHeaderLineColor = NSColor.colorWithCalibratedWhite_alpha_(0, .2)
topographyEditViewHeaderHighlightLineColor = NSColor.colorWithCalibratedWhite_alpha_(1, .5)
topographyEditViewNonSelectionColor = NSColor.colorWithCalibratedWhite_alpha_(0, .75)
topographyEditViewGroupColor = NSColor.colorWithCalibratedRed_green_blue_alpha_(.6, .6, .8, 1.0)
topographyEditViewExceptionColor = NSColor.colorWithCalibratedRed_green_blue_alpha_(.8, .5, .5, 1.0)
topographyEditViewPositiveColor = NSColor.colorWithCalibratedRed_green_blue_alpha_(0, 1, 0, .15)
topographyEditViewNegativeColor = NSColor.colorWithCalibratedRed_green_blue_alpha_(1, 0, 0, .15)
topographyEditViewZeroColor = NSColor.colorWithCalibratedRed_green_blue_alpha_(1, 1, 0, .25)

topographyViewLineColor = NSColor.colorWithCalibratedWhite_alpha_(1, .07)
topographyViewLineColor1 = NSColor.colorWithCalibratedWhite_alpha_(1, .28)
topographyViewLineColor2 = NSColor.colorWithCalibratedWhite_alpha_(1, .14)
topographyViewLineColor3 = NSColor.colorWithCalibratedWhite_alpha_(1, .07)
topographyViewExceptionColor = NSColor.colorWithCalibratedRed_green_blue_alpha_(0, 0, 1, .5)

glyphCountCellGroupBackgroundColor = NSColor.colorWithCalibratedRed_green_blue_alpha_(.3, .4, .7, .5)
glyphCountCellGroupGlowColor = NSColor.colorWithCalibratedRed_green_blue_alpha_(.2, .3, .5, 1.0)
glyphCountCellGlyphBackgroundColor = NSColor.colorWithCalibratedWhite_alpha_(.6, .5)
glyphCountCellGlyphGlowColor = NSColor.colorWithCalibratedWhite_alpha_(.45, 1.0)
glyphCountCellExceptionBackgroundColor = NSColor.colorWithCalibratedRed_green_blue_alpha_(1.0, .5, .5, .6)
glyphCountCellExceptionGlowColor = NSColor.colorWithCalibratedRed_green_blue_alpha_(.7, .5, .5, 1.0)
